/* THIS FILE IS AUTOGENERATED. DO NOT EDIT MANUALLY. */
/* eslint-disable */
/* prettier-ignore */

import {MessageLoader, TypedIntlMessageGetter, HandlerFunction, HookFunction, LinkFunction} from '@discord/intl';

export declare const messagesLoader: MessageLoader;

declare const messages: {
  /**
   * Key: `f77k/f`
   * 
   * ### Definition
   * ```text
   * ReCelled Account
   * ```
   * 
   * **Translated in all locales**
   */
  'RECELLED_ACCOUNT': TypedIntlMessageGetter<{}>,
  /**
   * Key: `3tbh1N`
   * 
   * ### Definition
   * ```text
   * Open {type} Folder
   * ```
   * 
   * ### Problems
   * 
   * Missing translations: `bg`, `da`, `el`, `he`, `hi`, `hr`, `lt`, `pt-PT`, `ro`
   */
  'RECELLED_ADDONS_FOLDER_OPEN': TypedIntlMessageGetter<{type: any}>,
  /**
   * Key: `+vuMU1`
   * 
   * ### Definition
   * ```text
   * Load Missing {type}
   * ```
   * 
   * ### Problems
   * 
   * Missing translations: `bg`, `da`, `el`, `he`, `hi`, `hr`, `lt`, `pt-PT`, `ro`
   */
  'RECELLED_ADDONS_LOAD_MISSING': TypedIntlMessageGetter<{type: any}>,
  /**
   * Key: `Q8Wp7u`
   * 
   * ### Definition
   * ```text
   * {type} ({count, number})
   * ```
   * 
   * ### Problems
   * 
   * Missing translations: `bg`, `da`, `el`, `he`, `hi`, `hr`, `lt`, `no`, `pt-PT`, `ro`
   */
  'RECELLED_ADDONS_TITLE_COUNT': TypedIntlMessageGetter<{count: number | string, type: any}>,
  /**
   * Key: `40RUT0`
   * 
   * ### Definition
   * ```text
   * by {author1}, {author2}, {author3}, and {count, plural, =1 {# other} other {# others}}
   * ```
   * 
   * ### Problems
   * 
   * Missing translations: `bg`, `da`, `el`, `he`, `hi`, `hr`, `lt`, `no`, `pt-PT`, `ro`
   */
  'RECELLED_ADDON_AUTHORS_MANY': TypedIntlMessageGetter<{author1: any, author2: any, author3: any, count: any | number | string}>,
  /**
   * Key: `4gW5cH`
   * 
   * ### Definition
   * ```text
   * by {author1}
   * ```
   * 
   * ### Problems
   * 
   * Missing translations: `bg`, `da`, `el`, `he`, `hi`, `hr`, `lt`, `no`, `pt-PT`, `ro`
   */
  'RECELLED_ADDON_AUTHORS_ONE': TypedIntlMessageGetter<{author1: any}>,
  /**
   * Key: `v14Ajo`
   * 
   * ### Definition
   * ```text
   * by {author1}, {author2}, and {author3}
   * ```
   * 
   * ### Problems
   * 
   * Missing translations: `bg`, `da`, `el`, `he`, `hi`, `hr`, `lt`, `pt-PT`, `ro`
   */
  'RECELLED_ADDON_AUTHORS_THREE': TypedIntlMessageGetter<{author1: any, author2: any, author3: any}>,
  /**
   * Key: `FPX72d`
   * 
   * ### Definition
   * ```text
   * by {author1} and {author2}
   * ```
   * 
   * ### Problems
   * 
   * Missing translations: `bg`, `da`, `el`, `he`, `hi`, `hr`, `lt`, `pt-PT`, `ro`
   */
  'RECELLED_ADDON_AUTHORS_TWO': TypedIntlMessageGetter<{author1: any, author2: any}>,
  /**
   * Key: `jgcD/P`
   * 
   * ### Definition
   * ```text
   * Browse {type}
   * ```
   * 
   * ### Problems
   * 
   * Missing translations: `ar`, `bg`, `da`, `el`, `he`, `hi`, `hr`, `hu`, `ko`, `lt`, `nl`, `no`, `pt-PT`, `ro`, `sv-SE`
   */
  'RECELLED_ADDON_BROWSE': TypedIntlMessageGetter<{type: any}>,
  /**
   * Key: `AwhLQ0`
   * 
   * ### Definition
   * ```text
   * Delete {type}
   * ```
   * 
   * ### Problems
   * 
   * Missing translations: `bg`, `da`, `el`, `he`, `hi`, `hr`, `lt`, `pt-PT`, `ro`
   */
  'RECELLED_ADDON_DELETE': TypedIntlMessageGetter<{type: any}>,
  /**
   * Key: `t5jssb`
   * 
   * ### Definition
   * ```text
   * Unreviewed {type}
   * ```
   * 
   * ### Problems
   * 
   * Missing translations: `ar`, `bg`, `da`, `el`, `he`, `hi`, `hr`, `hu`, `ko`, `lt`, `nl`, `no`, `pt-PT`, `ro`, `sv-SE`
   */
  'RECELLED_ADDON_NOT_REVIEWED': TypedIntlMessageGetter<{type: any}>,
  /**
   * Key: `bHrhd3`
   * 
   * ### Definition
   * ```text
   * This {type} has not been reviewed by the ReCelled team and could harm your computer. Use at your own risk.
   * ```
   * 
   * ### Problems
   * 
   * Missing translations: `ar`, `bg`, `da`, `el`, `he`, `hi`, `hr`, `hu`, `ko`, `lt`, `nl`, `no`, `pt-PT`, `ro`, `sv-SE`
   */
  'RECELLED_ADDON_NOT_REVIEWED_DESC': TypedIntlMessageGetter<{type: any}>,
  /**
   * Key: `+5XoBA`
   * 
   * ### Definition
   * ```text
   * Open {type} Page
   * ```
   * 
   * ### Problems
   * 
   * Missing translations: `bg`, `da`, `el`, `he`, `hi`, `hr`, `lt`, `pt-PT`, `ro`
   */
  'RECELLED_ADDON_PAGE_OPEN': TypedIntlMessageGetter<{type: any}>,
  /**
   * Key: `o7CQ3N`
   * 
   * ### Definition
   * ```text
   * Open {type} Profile
   * ```
   * 
   * ### Problems
   * 
   * Missing translations: `bg`, `da`, `el`, `he`, `hi`, `hr`, `lt`, `pt-PT`, `ro`
   */
  'RECELLED_ADDON_PROFILE_OPEN': TypedIntlMessageGetter<{type: any}>,
  /**
   * Key: `8Oyvub`
   * 
   * ### Definition
   * ```text
   * Reload {type}
   * ```
   * 
   * ### Problems
   * 
   * Missing translations: `bg`, `da`, `el`, `he`, `hi`, `hr`, `lt`, `pt-PT`, `ro`
   */
  'RECELLED_ADDON_RELOAD': TypedIntlMessageGetter<{type: any}>,
  /**
   * Key: `kVSZtb`
   * 
   * ### Definition
   * ```text
   * Open {type} Settings
   * ```
   * 
   * ### Problems
   * 
   * Missing translations: `bg`, `da`, `el`, `he`, `hi`, `hr`, `lt`, `pt-PT`, `ro`
   */
  'RECELLED_ADDON_SETTINGS': TypedIntlMessageGetter<{type: any}>,
  /**
   * Key: `S87y0t`
   * 
   * ### Definition
   * ```text
   * Uninstall {name}
   * ```
   * 
   * ### Problems
   * 
   * Missing translations: `bg`, `da`, `el`, `he`, `hi`, `hr`, `lt`, `pt-PT`, `ro`
   */
  'RECELLED_ADDON_UNINSTALL': TypedIntlMessageGetter<{name: any}>,
  /**
   * Key: `GB0yKS`
   * 
   * ### Definition
   * ```text
   * Are you sure you want to uninstall this {type}? This cannot be undone.
   * ```
   * 
   * ### Problems
   * 
   * Missing translations: `bg`, `da`, `el`, `he`, `hi`, `hr`, `lt`, `pt-PT`, `ro`
   */
  'RECELLED_ADDON_UNINSTALL_PROMPT_BODY': TypedIntlMessageGetter<{type: 'plugin' | any | string}>,
  /**
   * Key: `Ce4eYG`
   * 
   * ### Definition
   * ```text
   * ReCelled Server Booster
   * ```
   * 
   * ### Problems
   * 
   * Missing translations: `da`
   */
  'RECELLED_BADGES_BOOSTER': TypedIntlMessageGetter<{}>,
  /**
   * Key: `SW/dUV`
   * 
   * ### Definition
   * ```text
   * ReCelled Contributor
   * ```
   * 
   * **Translated in all locales**
   */
  'RECELLED_BADGES_CONTRIBUTOR': TypedIntlMessageGetter<{}>,
  /**
   * Key: `qI39XF`
   * 
   * ### Definition
   * ```text
   * ReCelled Developer
   * ```
   * 
   * **Translated in all locales**
   */
  'RECELLED_BADGES_DEVELOPER': TypedIntlMessageGetter<{}>,
  /**
   * Key: `98CWZW`
   * 
   * ### Definition
   * ```text
   * ReCelled Early User
   * ```
   * 
   * **Translated in all locales**
   */
  'RECELLED_BADGES_EARLY': TypedIntlMessageGetter<{}>,
  /**
   * Key: `fA5qPz`
   * 
   * ### Definition
   * ```text
   * ReCelled Bug Hunter
   * ```
   * 
   * **Translated in all locales**
   */
  'RECELLED_BADGES_HUNTER': TypedIntlMessageGetter<{}>,
  /**
   * Key: `fNZIxc`
   * 
   * ### Definition
   * ```text
   * ReCelled Staff
   * ```
   * 
   * **Translated in all locales**
   */
  'RECELLED_BADGES_STAFF': TypedIntlMessageGetter<{}>,
  /**
   * Key: `3ZFHaW`
   * 
   * ### Definition
   * ```text
   * ReCelled Support
   * ```
   * 
   * **Translated in all locales**
   */
  'RECELLED_BADGES_SUPPORT': TypedIntlMessageGetter<{}>,
  /**
   * Key: `Idmw2N`
   * 
   * ### Definition
   * ```text
   * ReCelled Translator
   * ```
   * 
   * **Translated in all locales**
   */
  'RECELLED_BADGES_TRANSLATOR': TypedIntlMessageGetter<{}>,
  /**
   * Key: `ZsF0ys`
   * 
   * ### Definition
   * ```text
   * Got It
   * ```
   * 
   * ### Problems
   * 
   * Missing translations: `bg`, `da`, `hr`
   */
  'RECELLED_BUTTON_GOT_IT': TypedIntlMessageGetter<{}>,
  /**
   * Key: `iXMVjY`
   * 
   * ### Definition
   * ```text
   * Download {type}
   * ```
   * 
   * ### Problems
   * 
   * Missing translations: `bg`, `da`, `hr`
   */
  'RECELLED_BUTTON_INSTALLER_DOWNLOAD': TypedIntlMessageGetter<{type: any}>,
  /**
   * Key: `0xX6AQ`
   * 
   * ### Definition
   * ```text
   * {type} Installed
   * ```
   * 
   * ### Problems
   * 
   * Missing translations: `bg`, `da`, `hr`
   */
  'RECELLED_BUTTON_INSTALLER_INSTALLED': TypedIntlMessageGetter<{type: any}>,
  /**
   * Key: `rP3GCw`
   * 
   * ### Definition
   * ```text
   * Cancel
   * ```
   * 
   * ### Problems
   * 
   * Missing translations: `bg`, `da`, `hr`
   */
  'RECELLED_CANCEL': TypedIntlMessageGetter<{}>,
  /**
   * Key: `0zd4+P`
   * 
   * ### Definition
   * ```text
   * Choose which addon to enable
   * ```
   * 
   * ### Problems
   * 
   * Missing translations: `ar`, `bg`, `da`, `he`, `hi`, `hr`, `hu`, `id`, `ko`, `lt`, `nl`, `no`, `pt-PT`, `ro`, `sk`, `vi`, `zh-CN`
   */
  'RECELLED_COMMAND_ADDONS_OPTION_ADDON_DESC': TypedIntlMessageGetter<{}>,
  /**
   * Key: `ALFHsr`
   * 
   * ### Definition
   * ```text
   * Disable a plugin or theme
   * ```
   * 
   * ### Problems
   * 
   * Missing translations: `bg`, `da`, `hr`
   */
  'RECELLED_COMMAND_DISABLE_DESC': TypedIntlMessageGetter<{}>,
  /**
   * Key: `4XE/cH`
   * 
   * ### Definition
   * ```text
   * {type} {name} has been disabled!
   * ```
   * 
   * ### Problems
   * 
   * Missing translations: `ar`, `bg`, `da`, `he`, `hi`, `hr`, `hu`, `id`, `ko`, `lt`, `nl`, `no`, `pt-PT`, `ro`, `sk`, `vi`, `zh-CN`
   */
  'RECELLED_COMMAND_DISABLE_MESSAGE_ENABLED': TypedIntlMessageGetter<{name: any, type: any}>,
  /**
   * Key: `wsvNr6`
   * 
   * ### Definition
   * ```text
   * disable
   * ```
   * 
   * ### Problems
   * 
   * Missing translations: `ar`, `bg`, `da`, `fr`, `he`, `hi`, `hr`, `hu`, `id`, `ko`, `lt`, `nl`, `no`, `pt-PT`, `ro`, `sk`, `vi`, `zh-CN`
   */
  'RECELLED_COMMAND_DISABLE_NAME': TypedIntlMessageGetter<{}>,
  /**
   * Key: `QwGpDA`
   * 
   * ### Definition
   * ```text
   * Choose which addon to disable
   * ```
   * 
   * ### Problems
   * 
   * Missing translations: `ar`, `bg`, `da`, `he`, `hi`, `hr`, `hu`, `id`, `ko`, `lt`, `nl`, `no`, `pt-PT`, `ro`, `sk`, `vi`, `zh-CN`
   */
  'RECELLED_COMMAND_DISABLE_OPTION_ADDON_DESC': TypedIntlMessageGetter<{}>,
  /**
   * Key: `wJNshI`
   * 
   * ### Definition
   * ```text
   * addon
   * ```
   * 
   * ### Problems
   * 
   * Missing translations: `ar`, `bg`, `da`, `he`, `hi`, `hr`, `hu`, `id`, `ko`, `lt`, `nl`, `no`, `pt-PT`, `ro`, `sk`, `vi`, `zh-CN`
   */
  'RECELLED_COMMAND_DISABLE_OPTION_ADDON_NAME': TypedIntlMessageGetter<{}>,
  /**
   * Key: `ICIckJ`
   * 
   * ### Definition
   * ```text
   * Enable a plugin or theme
   * ```
   * 
   * ### Problems
   * 
   * Missing translations: `bg`, `da`, `hi`, `hr`
   */
  'RECELLED_COMMAND_ENABLE_DESC': TypedIntlMessageGetter<{}>,
  /**
   * Key: `GHKvdX`
   * 
   * ### Definition
   * ```text
   * {type} {name} has been enabled!
   * ```
   * 
   * ### Problems
   * 
   * Missing translations: `ar`, `bg`, `da`, `he`, `hi`, `hr`, `hu`, `id`, `ko`, `lt`, `nl`, `no`, `pt-PT`, `ro`, `sk`, `vi`, `zh-CN`
   */
  'RECELLED_COMMAND_ENABLE_MESSAGE_ENABLED': TypedIntlMessageGetter<{name: any, type: any}>,
  /**
   * Key: `Ra0cFh`
   * 
   * ### Definition
   * ```text
   * enable
   * ```
   * 
   * ### Problems
   * 
   * Missing translations: `ar`, `bg`, `da`, `fr`, `he`, `hi`, `hr`, `hu`, `id`, `ko`, `lt`, `nl`, `no`, `pt-PT`, `ro`, `sk`, `vi`, `zh-CN`
   */
  'RECELLED_COMMAND_ENABLE_NAME': TypedIntlMessageGetter<{}>,
  /**
   * Key: `iaeR09`
   * 
   * ### Definition
   * ```text
   * addon
   * ```
   * 
   * ### Problems
   * 
   * Missing translations: `ar`, `bg`, `da`, `he`, `hi`, `hr`, `hu`, `id`, `ko`, `lt`, `nl`, `no`, `pt-PT`, `ro`, `sk`, `vi`, `zh-CN`
   */
  'RECELLED_COMMAND_ENABLE_OPTION_ADDON_NAME': TypedIntlMessageGetter<{}>,
  /**
   * Key: `hJJHlJ`
   * 
   * ### Definition
   * ```text
   * Something went wrong, please try again later. If this issue persists, please contact the ReCelled team.
   * ```
   * 
   * ### Problems
   * 
   * Missing translations: `ar`, `bg`, `da`, `fr`, `he`, `hi`, `hr`, `hu`, `id`, `ko`, `lt`, `nl`, `no`, `pt-PT`, `ro`, `sk`, `vi`, `zh-CN`
   */
  'RECELLED_COMMAND_ERROR_GENERIC': TypedIntlMessageGetter<{}>,
  /**
   * Key: `3vFzgI`
   * 
   * ### Definition
   * ```text
   * Install a plugin or theme
   * ```
   * 
   * ### Problems
   * 
   * Missing translations: `ar`, `bg`, `da`, `es-ES`, `fr`, `he`, `hi`, `hr`, `hu`, `id`, `ko`, `lt`, `nl`, `no`, `pt-PT`, `ro`, `ru`, `sk`, `sv-SE`, `vi`, `zh-CN`
   */
  'RECELLED_COMMAND_INSTALL_DESC': TypedIntlMessageGetter<{}>,
  /**
   * Key: `Q1hs3d`
   * 
   * ### Definition
   * ```text
   * install
   * ```
   * 
   * ### Problems
   * 
   * Missing translations: `ar`, `bg`, `da`, `es-ES`, `fr`, `he`, `hi`, `hr`, `hu`, `id`, `ko`, `lt`, `nl`, `no`, `pt-PT`, `ro`, `ru`, `sk`, `sv-SE`, `vi`, `zh-CN`
   */
  'RECELLED_COMMAND_INSTALL_NAME': TypedIntlMessageGetter<{}>,
  /**
   * Key: `epleV1`
   * 
   * ### Definition
   * ```text
   * Identifier of the addon to install from the source
   * ```
   * 
   * ### Problems
   * 
   * Missing translations: `ar`, `bg`, `da`, `es-ES`, `fr`, `he`, `hi`, `hr`, `hu`, `id`, `ko`, `lt`, `nl`, `no`, `pt-BR`, `pt-PT`, `ro`, `ru`, `sk`, `sv-SE`, `vi`, `zh-CN`
   */
  'RECELLED_COMMAND_INSTALL_OPTION_ADDON_DESC': TypedIntlMessageGetter<{}>,
  /**
   * Key: `v/r9HB`
   * 
   * ### Definition
   * ```text
   * addon
   * ```
   * 
   * ### Problems
   * 
   * Missing translations: `ar`, `bg`, `da`, `es-ES`, `fr`, `he`, `hi`, `hr`, `hu`, `id`, `ko`, `lt`, `nl`, `no`, `pt-BR`, `pt-PT`, `ro`, `ru`, `sk`, `sv-SE`, `vi`, `zh-CN`
   */
  'RECELLED_COMMAND_INSTALL_OPTION_ADDON_NAME': TypedIntlMessageGetter<{}>,
  /**
   * Key: `sNChlp`
   * 
   * ### Definition
   * ```text
   * If the source has multiple addons, specify which one to install
   * ```
   * 
   * ### Problems
   * 
   * Missing translations: `ar`, `bg`, `da`, `el`, `es-ES`, `fr`, `he`, `hi`, `hr`, `hu`, `id`, `ko`, `lt`, `nl`, `no`, `pt-BR`, `pt-PT`, `ro`, `ru`, `sk`, `sv-SE`, `vi`, `zh-CN`
   */
  'RECELLED_COMMAND_INSTALL_OPTION_ID_DESC': TypedIntlMessageGetter<{}>,
  /**
   * Key: `P8ZEnp`
   * 
   * ### Definition
   * ```text
   * id
   * ```
   * 
   * ### Problems
   * 
   * Missing translations: `ar`, `bg`, `da`, `el`, `es-ES`, `fr`, `he`, `hi`, `hr`, `hu`, `id`, `ko`, `lt`, `nl`, `no`, `pt-PT`, `ro`, `ru`, `sk`, `sv-SE`, `vi`, `zh-CN`
   */
  'RECELLED_COMMAND_INSTALL_OPTION_ID_NAME': TypedIntlMessageGetter<{}>,
  /**
   * Key: `lsSVIy`
   * 
   * ### Definition
   * ```text
   * Source to install the addon from
   * ```
   * 
   * ### Problems
   * 
   * Missing translations: `ar`, `bg`, `da`, `el`, `es-ES`, `fr`, `he`, `hi`, `hr`, `hu`, `id`, `ko`, `lt`, `nl`, `no`, `pt-BR`, `pt-PT`, `ro`, `ru`, `sk`, `sv-SE`, `vi`, `zh-CN`
   */
  'RECELLED_COMMAND_INSTALL_OPTION_SOURCE_DESC': TypedIntlMessageGetter<{}>,
  /**
   * Key: `sHTwiI`
   * 
   * ### Definition
   * ```text
   * source
   * ```
   * 
   * ### Problems
   * 
   * Missing translations: `ar`, `bg`, `da`, `el`, `es-ES`, `fr`, `he`, `hi`, `hr`, `hu`, `id`, `ko`, `lt`, `nl`, `no`, `pt-PT`, `ro`, `ru`, `sk`, `sv-SE`, `vi`, `zh-CN`
   */
  'RECELLED_COMMAND_INSTALL_OPTION_SOURCE_NAME': TypedIntlMessageGetter<{}>,
  /**
   * Key: `bW67HB`
   * 
   * ### Definition
   * ```text
   * List all plugins or themes
   * ```
   * 
   * ### Problems
   * 
   * Missing translations: `ar`, `bg`, `da`, `he`, `hi`, `hr`, `hu`, `id`, `ko`, `lt`, `nl`, `no`, `pt-PT`, `ro`, `sk`, `vi`, `zh-CN`
   */
  'RECELLED_COMMAND_LIST_DESC': TypedIntlMessageGetter<{}>,
  /**
   * Key: `cji2DQ`
   * 
   * ### Definition
   * ```text
   * You need to specify whether to send a plugin or theme list
   * ```
   * 
   * ### Problems
   * 
   * Missing translations: `ar`, `bg`, `da`, `es-ES`, `he`, `hi`, `hr`, `hu`, `id`, `ko`, `lt`, `nl`, `no`, `pt-PT`, `ro`, `sk`, `vi`, `zh-CN`
   */
  'RECELLED_COMMAND_LIST_ERROR_SPECIFY': TypedIntlMessageGetter<{}>,
  /**
   * Key: `NZgXqa`
   * 
   * ### Definition
   * ```text
   * Disabled {type}
   * ```
   * 
   * ### Problems
   * 
   * Missing translations: `ar`, `bg`, `da`, `es-ES`, `fr`, `he`, `hi`, `hr`, `hu`, `id`, `ko`, `lt`, `nl`, `no`, `pt-PT`, `ro`, `sk`, `vi`, `zh-CN`
   */
  'RECELLED_COMMAND_LIST_HEADER_DISABLED': TypedIntlMessageGetter<{type: any}>,
  /**
   * Key: `7dXEQE`
   * 
   * ### Definition
   * ```text
   * Enabled {type}
   * ```
   * 
   * ### Problems
   * 
   * Missing translations: `ar`, `bg`, `da`, `es-ES`, `fr`, `he`, `hi`, `hr`, `hu`, `id`, `ko`, `lt`, `nl`, `no`, `pt-PT`, `ro`, `sk`, `vi`, `zh-CN`
   */
  'RECELLED_COMMAND_LIST_HEADER_ENABLED': TypedIntlMessageGetter<{type: any}>,
  /**
   * Key: `STyfJy`
   * 
   * ### Definition
   * ```text
   * list
   * ```
   * 
   * ### Problems
   * 
   * Missing translations: `ar`, `bg`, `da`, `fr`, `he`, `hi`, `hr`, `hu`, `id`, `ko`, `lt`, `nl`, `no`, `pt-PT`, `ro`, `sk`, `vi`, `zh-CN`
   */
  'RECELLED_COMMAND_LIST_NAME': TypedIntlMessageGetter<{}>,
  /**
   * Key: `KWhq29`
   * 
   * ### Definition
   * ```text
   * Share the list publicly in chat
   * ```
   * 
   * ### Problems
   * 
   * Missing translations: `ar`, `bg`, `da`, `he`, `hi`, `hr`, `hu`, `id`, `ko`, `lt`, `nl`, `no`, `pt-PT`, `ro`, `sk`, `vi`, `zh-CN`
   */
  'RECELLED_COMMAND_LIST_OPTION_SEND_DESC': TypedIntlMessageGetter<{}>,
  /**
   * Key: `9bynlZ`
   * 
   * ### Definition
   * ```text
   * send
   * ```
   * 
   * ### Problems
   * 
   * Missing translations: `ar`, `bg`, `da`, `fr`, `he`, `hi`, `hr`, `hu`, `id`, `ko`, `lt`, `nl`, `no`, `pt-PT`, `ro`, `sk`, `vi`, `zh-CN`
   */
  'RECELLED_COMMAND_LIST_OPTION_SEND_NAME': TypedIntlMessageGetter<{}>,
  /**
   * Key: `sYOyIC`
   * 
   * ### Definition
   * ```text
   * Both
   * ```
   * 
   * ### Problems
   * 
   * Missing translations: `ar`, `bg`, `da`, `es-ES`, `fr`, `he`, `hi`, `hr`, `hu`, `id`, `ko`, `lt`, `nl`, `no`, `pt-PT`, `ro`, `sk`, `vi`, `zh-CN`
   */
  'RECELLED_COMMAND_LIST_OPTION_STATUS_CHOICE_BOTH': TypedIntlMessageGetter<{}>,
  /**
   * Key: `Wufqbm`
   * 
   * ### Definition
   * ```text
   * Disabled
   * ```
   * 
   * ### Problems
   * 
   * Missing translations: `ar`, `bg`, `da`, `es-ES`, `he`, `hi`, `hr`, `hu`, `id`, `ko`, `lt`, `nl`, `no`, `pt-PT`, `ro`, `sk`, `vi`, `zh-CN`
   */
  'RECELLED_COMMAND_LIST_OPTION_STATUS_CHOICE_DISABLED': TypedIntlMessageGetter<{}>,
  /**
   * Key: `s8QW9P`
   * 
   * ### Definition
   * ```text
   * Enabled
   * ```
   * 
   * ### Problems
   * 
   * Missing translations: `ar`, `bg`, `da`, `es-ES`, `he`, `hi`, `hr`, `hu`, `id`, `ko`, `lt`, `nl`, `no`, `pt-PT`, `ro`, `sk`, `vi`, `zh-CN`
   */
  'RECELLED_COMMAND_LIST_OPTION_STATUS_CHOICE_ENABLED': TypedIntlMessageGetter<{}>,
  /**
   * Key: `kwTBt7`
   * 
   * ### Definition
   * ```text
   * Whether to show addons that are enabled, disabled or both
   * ```
   * 
   * ### Problems
   * 
   * Missing translations: `ar`, `bg`, `da`, `es-ES`, `fr`, `he`, `hi`, `hr`, `hu`, `id`, `ko`, `lt`, `nl`, `no`, `pt-PT`, `ro`, `sk`, `vi`, `zh-CN`
   */
  'RECELLED_COMMAND_LIST_OPTION_STATUS_DESC': TypedIntlMessageGetter<{}>,
  /**
   * Key: `CEY5AA`
   * 
   * ### Definition
   * ```text
   * status
   * ```
   * 
   * ### Problems
   * 
   * Missing translations: `ar`, `bg`, `da`, `he`, `hi`, `hr`, `hu`, `id`, `ko`, `lt`, `nl`, `no`, `pt-PT`, `ro`, `sk`, `vi`, `zh-CN`
   */
  'RECELLED_COMMAND_LIST_OPTION_STATUS_NAME': TypedIntlMessageGetter<{}>,
  /**
   * Key: `mFCRCQ`
   * 
   * ### Definition
   * ```text
   * List Plugins
   * ```
   * 
   * ### Problems
   * 
   * Missing translations: `ar`, `bg`, `da`, `es-ES`, `fr`, `he`, `hi`, `hr`, `hu`, `id`, `ko`, `lt`, `nl`, `no`, `pt-PT`, `ro`, `sk`, `sv-SE`, `vi`, `zh-CN`
   */
  'RECELLED_COMMAND_LIST_OPTION_TYPE_CHOICE_PLUGIN': TypedIntlMessageGetter<{}>,
  /**
   * Key: `u5s2Tk`
   * 
   * ### Definition
   * ```text
   * List Themes
   * ```
   * 
   * ### Problems
   * 
   * Missing translations: `ar`, `bg`, `da`, `es-ES`, `fr`, `he`, `hi`, `hr`, `hu`, `id`, `ko`, `lt`, `nl`, `no`, `pt-PT`, `ro`, `sk`, `sv-SE`, `vi`, `zh-CN`
   */
  'RECELLED_COMMAND_LIST_OPTION_TYPE_CHOICE_THEME': TypedIntlMessageGetter<{}>,
  /**
   * Key: `3bZ5wM`
   * 
   * ### Definition
   * ```text
   * What type of addons to show
   * ```
   * 
   * ### Problems
   * 
   * Missing translations: `ar`, `bg`, `da`, `es-ES`, `fr`, `he`, `hi`, `hr`, `hu`, `id`, `ko`, `lt`, `nl`, `no`, `pt-PT`, `ro`, `sk`, `vi`, `zh-CN`
   */
  'RECELLED_COMMAND_LIST_OPTION_TYPE_DESC': TypedIntlMessageGetter<{}>,
  /**
   * Key: `s+p/jI`
   * 
   * ### Definition
   * ```text
   * type
   * ```
   * 
   * ### Problems
   * 
   * Missing translations: `ar`, `bg`, `da`, `fr`, `he`, `hi`, `hr`, `hu`, `id`, `ko`, `lt`, `nl`, `no`, `pt-PT`, `ro`, `sk`, `vi`, `zh-CN`
   */
  'RECELLED_COMMAND_LIST_OPTION_TYPE_NAME': TypedIntlMessageGetter<{}>,
  /**
   * Key: `1IshoK`
   * 
   * ### Definition
   * ```text
   * Include version numbers in the list
   * ```
   * 
   * ### Problems
   * 
   * Missing translations: `ar`, `bg`, `da`, `he`, `hi`, `hr`, `hu`, `id`, `ko`, `lt`, `nl`, `no`, `pt-PT`, `ro`, `sk`, `vi`, `zh-CN`
   */
  'RECELLED_COMMAND_LIST_OPTION_VERSION_DESC': TypedIntlMessageGetter<{}>,
  /**
   * Key: `DD3oZW`
   * 
   * ### Definition
   * ```text
   * version
   * ```
   * 
   * ### Problems
   * 
   * Missing translations: `ar`, `bg`, `da`, `fr`, `he`, `hi`, `hr`, `hu`, `id`, `ko`, `lt`, `nl`, `no`, `pt-PT`, `ro`, `sk`, `sv-SE`, `vi`, `zh-CN`
   */
  'RECELLED_COMMAND_LIST_OPTION_VERSION_NAME': TypedIntlMessageGetter<{}>,
  /**
   * Key: `g+PEam`
   * 
   * ### Definition
   * ```text
   * Reload a plugin or theme
   * ```
   * 
   * ### Problems
   * 
   * Missing translations: `bg`, `da`, `he`, `hi`, `hr`, `lt`
   */
  'RECELLED_COMMAND_RELOAD_DESC': TypedIntlMessageGetter<{}>,
  /**
   * Key: `djK4tL`
   * 
   * ### Definition
   * ```text
   * {type} {name} has been reloaded!
   * ```
   * 
   * ### Problems
   * 
   * Missing translations: `ar`, `bg`, `da`, `he`, `hi`, `hr`, `hu`, `id`, `ko`, `lt`, `nl`, `no`, `pt-PT`, `ro`, `sk`, `vi`, `zh-CN`
   */
  'RECELLED_COMMAND_RELOAD_MESSAGE_ENABLED': TypedIntlMessageGetter<{name: any, type: any}>,
  /**
   * Key: `C0Rxo6`
   * 
   * ### Definition
   * ```text
   * reload
   * ```
   * 
   * ### Problems
   * 
   * Missing translations: `ar`, `bg`, `da`, `fr`, `he`, `hi`, `hr`, `hu`, `id`, `ko`, `lt`, `nl`, `no`, `pt-PT`, `ro`, `sk`, `vi`, `zh-CN`
   */
  'RECELLED_COMMAND_RELOAD_NAME': TypedIntlMessageGetter<{}>,
  /**
   * Key: `0cg0pq`
   * 
   * ### Definition
   * ```text
   * Choose which addon to reload
   * ```
   * 
   * ### Problems
   * 
   * Missing translations: `ar`, `bg`, `da`, `he`, `hi`, `hr`, `hu`, `id`, `ko`, `lt`, `nl`, `no`, `pt-PT`, `ro`, `sk`, `vi`, `zh-CN`
   */
  'RECELLED_COMMAND_RELOAD_OPTION_ADDON_DESC': TypedIntlMessageGetter<{}>,
  /**
   * Key: `F0h5/v`
   * 
   * ### Definition
   * ```text
   * addon
   * ```
   * 
   * ### Problems
   * 
   * Missing translations: `ar`, `bg`, `da`, `fr`, `he`, `hi`, `hr`, `hu`, `id`, `ko`, `lt`, `nl`, `no`, `pt-PT`, `ro`, `sk`, `vi`, `zh-CN`
   */
  'RECELLED_COMMAND_RELOAD_OPTION_ADDON_NAME': TypedIntlMessageGetter<{}>,
  /**
   * Key: `2ZZqFB`
   * 
   * ### Definition
   * ```text
   * Success
   * ```
   * 
   * ### Problems
   * 
   * Missing translations: `ar`, `bg`, `da`, `fr`, `he`, `hi`, `hr`, `hu`, `id`, `ko`, `lt`, `nl`, `no`, `pt-PT`, `ro`, `sk`, `vi`, `zh-CN`
   */
  'RECELLED_COMMAND_SUCCESS_GENERIC': TypedIntlMessageGetter<{}>,
  /**
   * Key: `TPm8BQ`
   * 
   * ### Definition
   * ```text
   * Confirm
   * ```
   * 
   * ### Problems
   * 
   * Missing translations: `bg`, `hr`
   */
  'RECELLED_CONFIRM': TypedIntlMessageGetter<{}>,
  /**
   * Key: `038KnZ`
   * 
   * ### Definition
   * ```text
   * Install
   * ```
   * 
   * ### Problems
   * 
   * Missing translations: `bg`, `da`, `el`, `he`, `hi`, `hr`, `lt`, `no`, `pt-PT`, `ro`
   */
  'RECELLED_CONFIRM_INSTALL': TypedIntlMessageGetter<{}>,
  /**
   * Key: `trDeyc`
   * 
   * ### Definition
   * ```text
   * You are currently running ReCelled in developer mode and ReCelled will not be able to update itself. [Switch to production mode]({url}).
   * ```
   * 
   * ### Problems
   * 
   * Missing translations: `ar`, `bg`, `da`, `el`, `he`, `hi`, `hr`, `hu`, `ko`, `lt`, `nl`, `no`, `pt-PT`, `ro`, `sv-SE`
   */
  'RECELLED_DEVELOPER_MODE_WARNING': TypedIntlMessageGetter<{$link?: LinkFunction, url: any}>,
  /**
   * Key: `hOnI9/`
   * 
   * ### Definition
   * ```text
   * {name} is already installed.
   * ```
   * 
   * ### Problems
   * 
   * Missing translations: `bg`, `da`, `el`, `he`, `hi`, `hr`, `lt`
   */
  'RECELLED_ERROR_ALREADY_INSTALLED': TypedIntlMessageGetter<{name: any}>,
  /**
   * Key: `47SRSU`
   * 
   * ### Definition
   * ```text
   * An error occurred while executing the command:
   * ```
   * 
   * ### Problems
   * 
   * Missing translations: `bg`, `da`, `he`, `hi`, `hr`, `lt`
   */
  'RECELLED_ERROR_AN_ERROR_OCCURRED_COMMAND': TypedIntlMessageGetter<{}>,
  /**
   * Key: `vAKU7u`
   * 
   * ### Definition
   * ```text
   * Check the console for more details.
   * ```
   * 
   * ### Problems
   * 
   * Missing translations: `bg`, `da`, `he`, `hi`, `hr`, `lt`
   */
  'RECELLED_ERROR_CHECK_CONSOLE': TypedIntlMessageGetter<{}>,
  /**
   * Key: `WA0cQk`
   * 
   * ### Definition
   * ```text
   * General Settings
   * ```
   * 
   * ### Problems
   * 
   * Missing translations: `hi`
   */
  'RECELLED_GENERAL_SETTINGS': TypedIntlMessageGetter<{}>,
  /**
   * Key: `DkLotL`
   * 
   * ### Definition
   * ```text
   * ReCelled Translations
   * ```
   * 
   * ### Problems
   * 
   * Missing translations: `ar`, `bg`, `da`, `el`, `he`, `hi`, `hr`, `hu`, `lt`, `no`, `pt-PT`, `ro`, `sv-SE`
   */
  'RECELLED_I18N': TypedIntlMessageGetter<{}>,
  /**
   * Key: `fU4Hoa`
   * 
   * ### Definition
   * ```text
   * Want to help translate ReCelled? Go to our [Weblate]({weblateUrl})!
   * ```
   * 
   * ### Problems
   * 
   * Missing translations: `bg`, `da`, `hi`
   */
  'RECELLED_I18N_CONTRIBUTE': TypedIntlMessageGetter<{$link?: LinkFunction, weblateUrl: any}>,
  /**
   * Key: `HhE3rq`
   * 
   * ### Definition
   * ```text
   * ReCelled: {translated,number}% translated
   * ```
   * 
   * ### Problems
   * 
   * Missing translations: `bg`, `hi`
   */
  'RECELLED_I18N_TRANSLATED_PERCENTAGE': TypedIntlMessageGetter<{translated: number | string}>,
  /**
   * Key: `1TGTt7`
   * 
   * ### Definition
   * ```text
   * Do you want to install {name} {authors}?
   * ```
   * 
   * ### Problems
   * 
   * Missing translations: `bg`, `da`, `el`, `he`, `hi`, `hr`, `lt`, `no`, `pt-PT`, `ro`
   */
  'RECELLED_INSTALLER_INSTALL_PROMPT_BODY': TypedIntlMessageGetter<{authors: any, name: any}>,
  /**
   * Key: `GBKiWl`
   * 
   * ### Definition
   * ```text
   * View in Store
   * ```
   * 
   * ### Problems
   * 
   * Missing translations: `ar`, `bg`, `da`, `el`, `he`, `hi`, `hr`, `hu`, `ko`, `lt`, `nl`, `no`, `pt-PT`, `ro`, `sv-SE`, `zh-CN`
   */
  'RECELLED_INSTALLER_OPEN_STORE': TypedIntlMessageGetter<{}>,
  /**
   * Key: `vjTOhY`
   * 
   * ### Definition
   * ```text
   * Install {type}
   * ```
   * 
   * ### Problems
   * 
   * Missing translations: `bg`, `da`, `he`, `hi`, `hr`, `lt`
   */
  'RECELLED_INSTALL_MODAL_HEADER': TypedIntlMessageGetter<{type: any}>,
  /**
   * Key: `+UkKJy`
   * 
   * ### Definition
   * ```text
   * Link it now
   * ```
   * 
   * ### Problems
   * 
   * Missing translations: `bg`, `da`, `hi`
   */
  'RECELLED_LINK_NOW': TypedIntlMessageGetter<{}>,
  /**
   * Key: `H5Uu9/`
   * 
   * ### Definition
   * ```text
   * {count, plural, =1 {# match} other {# matches}}
   * ```
   * 
   * ### Problems
   * 
   * Missing translations: `bg`, `da`, `el`, `he`, `hi`, `hr`, `hu`, `lt`, `no`, `pt-PT`, `ro`, `sv-SE`, `zh-CN`
   */
  'RECELLED_LIST_RESULTS': TypedIntlMessageGetter<{count: any | number | string}>,
  /**
   * Key: `Yyadxc`
   * 
   * ### Definition
   * ```text
   * Join Server
   * ```
   * 
   * ### Problems
   * 
   * Missing translations: `bg`, `da`, `el`, `he`, `hi`, `hr`, `lt`, `ro`
   */
  'RECELLED_NOTICES_JOIN_SERVER_BUTTON': TypedIntlMessageGetter<{}>,
  /**
   * Key: `1LNq6e`
   * 
   * ### Definition
   * ```text
   * Welcome! ReCelled has been successfully injected into your Discord client. Feel free to join our Discord server for announcements, support and more!
   * ```
   * 
   * ### Problems
   * 
   * Missing translations: `bg`, `da`, `el`, `he`, `hi`, `hr`, `lt`, `ro`
   */
  'RECELLED_NOTICES_WELCOME_NEW_USER': TypedIntlMessageGetter<{}>,
  /**
   * Key: `BWZ129`
   * 
   * ### Definition
   * ```text
   * No {type} installed.
   * ```
   * 
   * ### Problems
   * 
   * Missing translations: `bg`, `da`, `el`, `he`, `hi`, `hr`, `lt`, `no`, `pt-PT`, `ro`
   */
  'RECELLED_NO_ADDONS_INSTALLED': TypedIntlMessageGetter<{type: any}>,
  /**
   * Key: `UMg+QU`
   * 
   * ### Definition
   * ```text
   * No {type} matched your search.
   * ```
   * 
   * ### Problems
   * 
   * Missing translations: `bg`, `da`, `el`, `he`, `hi`, `hr`, `lt`, `no`, `pt-PT`, `ro`
   */
  'RECELLED_NO_ADDON_RESULTS': TypedIntlMessageGetter<{type: any}>,
  /**
   * Key: `aBtago`
   * 
   * ### Definition
   * ```text
   * OK
   * ```
   * 
   * ### Problems
   * 
   * Missing translations: `bg`, `da`, `hr`, `no`
   */
  'RECELLED_OK': TypedIntlMessageGetter<{}>,
  /**
   * Key: `cgihWl`
   * 
   * ### Definition
   * ```text
   * Plugin
   * ```
   * 
   * ### Problems
   * 
   * Missing translations: `bg`, `da`, `el`, `he`, `hi`, `hr`, `lt`, `ro`
   */
  'RECELLED_PLUGIN': TypedIntlMessageGetter<{}>,
  /**
   * Key: `ZbGCy8`
   * 
   * ### Definition
   * ```text
   * Plugins
   * ```
   * 
   * ### Problems
   * 
   * Missing translations: `hi`
   */
  'RECELLED_PLUGINS': TypedIntlMessageGetter<{}>,
  /**
   * Key: `8oIDtb`
   * 
   * ### Definition
   * ```text
   * Copied!
   * ```
   * 
   * ### Problems
   * 
   * Missing translations: `bg`, `da`, `hi`, `hr`, `no`
   */
  'RECELLED_PLUGIN_EMBED_COPIED': TypedIntlMessageGetter<{}>,
  /**
   * Key: `ZRF0KC`
   * 
   * ### Definition
   * ```text
   * Copy Link
   * ```
   * 
   * ### Problems
   * 
   * Missing translations: `bg`, `da`, `hi`, `hr`, `no`
   */
  'RECELLED_PLUGIN_EMBED_COPY': TypedIntlMessageGetter<{}>,
  /**
   * Key: `MiOWUF`
   * 
   * ### Definition
   * ```text
   * View Repo
   * ```
   * 
   * ### Problems
   * 
   * Missing translations: `bg`, `da`, `hi`, `hr`, `no`
   */
  'RECELLED_PLUGIN_EMBED_VIEW_REPO': TypedIntlMessageGetter<{}>,
  /**
   * Key: `PEw8Pz`
   * 
   * ### Definition
   * ```text
   * What is this?
   * ```
   * 
   * ### Problems
   * 
   * Missing translations: `bg`, `da`, `hi`, `hr`, `no`
   */
  'RECELLED_PLUGIN_EMBED_WHATISTHIS': TypedIntlMessageGetter<{}>,
  /**
   * Key: `5oq5bm`
   * 
   * ### Definition
   * ```text
   * This is a ReCelled feature. It allows you to install plugins or themes straight from chat.
   * Simply hit the install button on the embed.
   * ```
   * 
   * ### Problems
   * 
   * Missing translations: `bg`, `da`, `hi`, `hr`, `no`
   */
  'RECELLED_PLUGIN_EMBED_WHATISTHIS_CONTENT': TypedIntlMessageGetter<{}>,
  /**
   * Key: `e9QObm`
   * 
   * ### Definition
   * ```text
   * {name} requires a reload to work properly. Reload now?
   * ```
   * 
   * ### Problems
   * 
   * Missing translations: `bg`, `da`, `el`, `he`, `hi`, `hr`, `lt`, `no`, `pt-PT`, `ro`
   */
  'RECELLED_PLUGIN_INSTALL_RELOAD_PROMPT_BODY': TypedIntlMessageGetter<{name: any}>,
  /**
   * Key: `7e9QwM`
   * 
   * ### Definition
   * ```text
   * Quick CSS
   * ```
   * 
   * ### Problems
   * 
   * Missing translations: `bg`, `hi`
   */
  'RECELLED_QUICKCSS': TypedIntlMessageGetter<{}>,
  /**
   * Key: `bJjxRU`
   * 
   * ### Definition
   * ```text
   * Apply Changes
   * ```
   * 
   * ### Problems
   * 
   * Missing translations: `bg`, `da`, `el`, `he`, `hi`, `hr`, `lt`, `no`, `pt-PT`, `ro`
   */
  'RECELLED_QUICKCSS_CHANGES_APPLY': TypedIntlMessageGetter<{}>,
  /**
   * Key: `+sdlQU`
   * 
   * ### Definition
   * ```text
   * Open Quick CSS Folder
   * ```
   * 
   * ### Problems
   * 
   * Missing translations: `bg`, `da`, `el`, `he`, `hi`, `hr`, `lt`, `no`, `pt-PT`, `ro`
   */
  'RECELLED_QUICKCSS_FOLDER_OPEN': TypedIntlMessageGetter<{}>,
  /**
   * Key: `mM0E7e`
   * 
   * ### Definition
   * ```text
   * Reload
   * ```
   * 
   * ### Problems
   * 
   * Missing translations: `bg`, `da`, `el`, `he`, `hi`, `hr`, `lt`, `no`, `pt-PT`, `ro`
   */
  'RECELLED_RELOAD': TypedIntlMessageGetter<{}>,
  /**
   * Key: `vGHEjY`
   * 
   * ### Definition
   * ```text
   * Restart
   * ```
   * 
   * ### Problems
   * 
   * Missing translations: `ar`, `bg`, `da`, `el`, `he`, `hi`, `hr`, `hu`, `ko`, `lt`, `nl`, `no`, `pt-PT`, `ro`, `sk`, `sv-SE`, `zh-CN`
   */
  'RECELLED_RESTART': TypedIntlMessageGetter<{}>,
  /**
   * Key: `sTDVmp`
   * 
   * ### Definition
   * ```text
   * Search for a {type}
   * ```
   * 
   * ### Problems
   * 
   * Missing translations: `bg`, `da`, `el`, `he`, `hi`, `hr`, `lt`, `no`, `pt-PT`, `ro`
   */
  'RECELLED_SEARCH_FOR_ADDON': TypedIntlMessageGetter<{type: any}>,
  /**
   * Key: `J8xXbG`
   * 
   * ### Definition
   * ```text
   * Show Addon Embeds
   * ```
   * 
   * ### Problems
   * 
   * Missing translations: `ar`, `bg`, `da`, `el`, `he`, `hi`, `hr`, `hu`, `ko`, `lt`, `nl`, `no`, `pt-PT`, `ro`, `sv-SE`, `zh-CN`
   */
  'RECELLED_SETTINGS_ADDON_EMBEDS': TypedIntlMessageGetter<{}>,
  /**
   * Key: `5R5DEB`
   * 
   * ### Definition
   * ```text
   * Show a card with information on an addon when a store/install link is shared in chat.
   * ```
   * 
   * ### Problems
   * 
   * Missing translations: `ar`, `bg`, `da`, `el`, `he`, `hi`, `hr`, `hu`, `ko`, `lt`, `nl`, `no`, `pt-PT`, `ro`, `sv-SE`, `zh-CN`
   */
  'RECELLED_SETTINGS_ADDON_EMBEDS_DESC': TypedIntlMessageGetter<{}>,
  /**
   * Key: `u/AcmJ`
   * 
   * ### Definition
   * ```text
   * Advanced Settings
   * ```
   * 
   * ### Problems
   * 
   * Missing translations: `ar`, `bg`, `da`, `el`, `he`, `hi`, `hr`, `hu`, `ko`, `lt`, `nl`, `no`, `pt-PT`, `ro`, `sv-SE`
   */
  'RECELLED_SETTINGS_ADVANCED': TypedIntlMessageGetter<{}>,
  /**
   * Key: `zl/Hk5`
   * 
   * ### Definition
   * ```text
   * Don't touch stuff in here if you don't know what you're doing. Unexpected things can happen to your cat.
   * ```
   * 
   * ### Problems
   * 
   * Missing translations: `bg`, `da`, `hi`
   */
  'RECELLED_SETTINGS_ADVANCED_DESC': TypedIntlMessageGetter<{}>,
  /**
   * Key: `wKvfV1`
   * 
   * ### Definition
   * ```text
   * Backend URL
   * ```
   * 
   * ### Problems
   * 
   * Missing translations: `bg`, `da`, `hi`
   */
  'RECELLED_SETTINGS_BACKEND': TypedIntlMessageGetter<{}>,
  /**
   * Key: `ZvYuTE`
   * 
   * ### Definition
   * ```text
   * URL used to fetch some assets and to query ReCelled's REST API.
   * ```
   * 
   * ### Problems
   * 
   * Missing translations: `bg`, `da`, `hi`
   */
  'RECELLED_SETTINGS_BACKEND_DESC': TypedIntlMessageGetter<{}>,
  /**
   * Key: `J2eAaG`
   * 
   * ### Definition
   * ```text
   * Enable ReCelled Badges
   * ```
   * 
   * ### Problems
   * 
   * Missing translations: `ar`, `bg`, `da`, `el`, `he`, `hi`, `hr`, `hu`, `lt`, `no`, `pt-PT`, `ro`, `sv-SE`
   */
  'RECELLED_SETTINGS_BADGES': TypedIntlMessageGetter<{}>,
  /**
   * Key: `b63dZG`
   * 
   * ### Definition
   * ```text
   * Show custom ReCelled badges on user profiles.
   * ```
   * 
   * ### Problems
   * 
   * Missing translations: `ar`, `bg`, `da`, `el`, `he`, `hi`, `hr`, `hu`, `lt`, `no`, `pt-PT`, `ro`, `sv-SE`
   */
  'RECELLED_SETTINGS_BADGES_DESC': TypedIntlMessageGetter<{}>,
  /**
   * Key: `WJd5oa`
   * 
   * ### Definition
   * ```text
   * Custom Title Bar
   * ```
   * 
   * ### Problems
   * 
   * Missing translations: `ar`, `bg`, `cs`, `da`, `de`, `el`, `en-GB`, `es-ES`, `fi`, `fr`, `he`, `hi`, `hr`, `hu`, `id`, `it`, `ja`, `ko`, `lt`, `nl`, `no`, `pl`, `pt-BR`, `pt-PT`, `ro`, `ru`, `sk`, `sv-SE`, `tr`, `uk`, `vi`, `zh-CN`, `zh-TW`
   */
  'RECELLED_SETTINGS_CUSTOM_TITLE_BAR': TypedIntlMessageGetter<{}>,
  /**
   * Key: `0j2kc3`
   * 
   * ### Definition
   * ```text
   * Use Discord's custom title bar instead of the system title bar. **Requires restart**.
   * ```
   * 
   * ### Problems
   * 
   * Missing translations: `ar`, `bg`, `cs`, `da`, `de`, `el`, `en-GB`, `es-ES`, `fi`, `fr`, `he`, `hi`, `hr`, `hu`, `id`, `it`, `ja`, `ko`, `lt`, `nl`, `no`, `pl`, `pt-BR`, `pt-PT`, `ro`, `ru`, `sk`, `sv-SE`, `tr`, `uk`, `vi`, `zh-CN`, `zh-TW`
   */
  'RECELLED_SETTINGS_CUSTOM_TITLE_BAR_DESC': TypedIntlMessageGetter<{$b?: HookFunction}>,
  /**
   * Key: `NH8bBQ`
   * 
   * ### Definition
   * ```text
   * Reconnect Dev Companion
   * ```
   * 
   * ### Problems
   * 
   * Missing translations: `ar`, `bg`, `da`, `el`, `he`, `hi`, `hr`, `hu`, `ko`, `lt`, `nl`, `no`, `pt-PT`, `ro`, `sv-SE`
   */
  'RECELLED_SETTINGS_DEV_COMPANION': TypedIntlMessageGetter<{}>,
  /**
   * Key: `+3n/h4`
   * 
   * ### Definition
   * ```text
   * Reconnects the Dev Companion coremod to the VSCode extension.
   * ```
   * 
   * ### Problems
   * 
   * Missing translations: `ar`, `bg`, `da`, `el`, `he`, `hi`, `hr`, `hu`, `ko`, `lt`, `nl`, `no`, `pt-PT`, `ro`, `sv-SE`
   */
  'RECELLED_SETTINGS_DEV_COMPANION_DESC': TypedIntlMessageGetter<{}>,
  /**
   * Key: `7CuDRE`
   * 
   * ### Definition
   * ```text
   * Reconnect
   * ```
   * 
   * ### Problems
   * 
   * Missing translations: `ar`, `bg`, `da`, `el`, `he`, `hi`, `hr`, `hu`, `ko`, `lt`, `nl`, `no`, `pt-PT`, `ro`, `sv-SE`
   */
  'RECELLED_SETTINGS_DEV_COMPANION_RECONNECT': TypedIntlMessageGetter<{}>,
  /**
   * Key: `yfGwWl`
   * 
   * ### Definition
   * ```text
   * Enable Discord Experiments
   * ```
   * 
   * ### Problems
   * 
   * Missing translations: `bg`, `da`, `hi`
   */
  'RECELLED_SETTINGS_DISCORD_EXPERIMENTS': TypedIntlMessageGetter<{}>,
  /**
   * Key: `kgvU+v`
   * 
   * ### Definition
   * ```text
   * ****WARNING:**** Enabling this gives you access to features that can be detected by Discord and may result in an ****account termination****. ReCelled is **not responsible** for what you do with this feature. Leave it disabled if you are unsure. The ReCelled Team will **not** provide any support regarding any experiment. **Requires restart**.
   * ```
   * 
   * ### Problems
   * 
   * Missing translations: `bg`, `da`, `hi`
   */
  'RECELLED_SETTINGS_DISCORD_EXPERIMENTS_DESC': TypedIntlMessageGetter<{$b?: HookFunction}>,
  /**
   * Key: `WJQncH`
   * 
   * ### Definition
   * ```text
   * Component stack:
   * ```
   * 
   * ### Problems
   * 
   * Missing translations: `bg`, `da`, `el`, `he`, `hi`, `hr`, `lt`, `pt-PT`, `ro`
   */
  'RECELLED_SETTINGS_ERROR_COMPONENT_STACK': TypedIntlMessageGetter<{}>,
  /**
   * Key: `+L5WXV`
   * 
   * ### Definition
   * ```text
   * Something went wrong rendering this element!
   * ```
   * 
   * ### Problems
   * 
   * Missing translations: `bg`, `da`, `el`, `he`, `hi`, `hr`, `lt`, `pt-PT`, `ro`
   */
  'RECELLED_SETTINGS_ERROR_HEADER': TypedIntlMessageGetter<{}>,
  /**
   * Key: `+fqji4`
   * 
   * ### Definition
   * ```text
   * Plugin: {name}
   * ```
   * 
   * ### Problems
   * 
   * Missing translations: `ar`, `bg`, `da`, `el`, `es-ES`, `fr`, `he`, `hi`, `hr`, `hu`, `id`, `ko`, `lt`, `nl`, `no`, `pt-PT`, `ro`, `ru`, `sk`, `sv-SE`, `vi`, `zh-CN`
   */
  'RECELLED_SETTINGS_ERROR_PLUGIN_NAME': TypedIntlMessageGetter<{name: any}>,
  /**
   * Key: `cKEPfH`
   * 
   * ### Definition
   * ```text
   * An error occurred while rendering settings panel.
   * ```
   * 
   * ### Problems
   * 
   * Missing translations: `bg`, `da`, `el`, `he`, `hi`, `hr`, `lt`, `pt-PT`, `ro`
   */
  'RECELLED_SETTINGS_ERROR_RENDER_PANEL': TypedIntlMessageGetter<{}>,
  /**
   * Key: `+q42Ul`
   * 
   * ### Definition
   * ```text
   * Check console for details.
   * ```
   * 
   * ### Problems
   * 
   * Missing translations: `bg`, `da`, `el`, `he`, `hi`, `hr`, `lt`, `no`, `pt-PT`, `ro`
   */
  'RECELLED_SETTINGS_ERROR_SUB_HEADER': TypedIntlMessageGetter<{}>,
  /**
   * Key: `ZwWyub`
   * 
   * ### Definition
   * ```text
   * Keep token stored
   * ```
   * 
   * ### Problems
   * 
   * Missing translations: `da`, `hi`
   */
  'RECELLED_SETTINGS_KEEP_TOKEN': TypedIntlMessageGetter<{}>,
  /**
   * Key: `JaMzuL`
   * 
   * ### Definition
   * ```text
   * Prevents Discord from removing your token from localStorage, reducing the numbers of unwanted logouts.
   * ```
   * 
   * ### Problems
   * 
   * Missing translations: `bg`, `da`, `hi`
   */
  'RECELLED_SETTINGS_KEEP_TOKEN_DESC': TypedIntlMessageGetter<{}>,
  /**
   * Key: `6uHkzs`
   * 
   * ### Definition
   * ```text
   * Eradicate Clyde
   * ```
   * 
   * ### Problems
   * 
   * Missing translations: `bg`, `da`, `hi`
   */
  'RECELLED_SETTINGS_NO_CLYDE': TypedIntlMessageGetter<{}>,
  /**
   * Key: `Vzg8nJ`
   * 
   * ### Definition
   * ```text
   * Replaces [Clyde]({clydeUrl}) in ReCelled commands with a mixed range of avatars and usernames selected by plug-in developers - fallbacks to "ReCelled" by default.
   * ```
   * 
   * ### Problems
   * 
   * Missing translations: `bg`, `da`, `hi`
   */
  'RECELLED_SETTINGS_NO_CLYDE_DESC': TypedIntlMessageGetter<{$link?: LinkFunction, clydeUrl: any}>,
  /**
   * Key: `mnDR09`
   * 
   * ### Definition
   * ```text
   * Overlay DevTools
   * ```
   * 
   * ### Problems
   * 
   * Missing translations: `bg`, `da`, `hi`
   */
  'RECELLED_SETTINGS_OVERLAY': TypedIntlMessageGetter<{}>,
  /**
   * Key: `yol6s7`
   * 
   * ### Definition
   * ```text
   * Opens a DevTools window that lets you inspect what's happening within Discord's in-game overlay.
   * ```
   * 
   * ### Problems
   * 
   * Missing translations: `bg`, `da`, `hi`
   */
  'RECELLED_SETTINGS_OVERLAY_DESC': TypedIntlMessageGetter<{}>,
  /**
   * Key: `Zg7J8/`
   * 
   * ### Definition
   * ```text
   * Automatically Apply Quick CSS
   * ```
   * 
   * ### Problems
   * 
   * Missing translations: `ar`, `bg`, `da`, `el`, `he`, `hi`, `hr`, `hu`, `ko`, `lt`, `nl`, `no`, `pt-PT`, `ro`, `sv-SE`
   */
  'RECELLED_SETTINGS_QUICKCSS_AUTO_APPLY': TypedIntlMessageGetter<{}>,
  /**
   * Key: `++P5CQ`
   * 
   * ### Definition
   * ```text
   * Automatically apply changes to Quick CSS as you type.
   * ```
   * 
   * ### Problems
   * 
   * Missing translations: `ar`, `bg`, `da`, `el`, `he`, `hi`, `hr`, `hu`, `ko`, `lt`, `nl`, `no`, `pt-PT`, `ro`, `sv-SE`
   */
  'RECELLED_SETTINGS_QUICKCSS_AUTO_APPLY_DESC': TypedIntlMessageGetter<{}>,
  /**
   * Key: `ROnYIy`
   * 
   * ### Definition
   * ```text
   * Enable React DevTools
   * ```
   * 
   * ### Problems
   * 
   * Missing translations: `ar`, `bg`, `da`, `el`, `he`, `hi`, `hr`, `hu`, `ko`, `lt`, `nl`, `no`, `pt-PT`, `ro`, `sv-SE`
   */
  'RECELLED_SETTINGS_REACT_DEVTOOLS': TypedIntlMessageGetter<{}>,
  /**
   * Key: `idzB5O`
   * 
   * ### Definition
   * ```text
   * Loads the React DevTools extension, allowing you to inspect the React tree and debug more easily. **Requires restart**.
   * ```
   * 
   * ### Problems
   * 
   * Missing translations: `ar`, `bg`, `da`, `el`, `he`, `hi`, `hr`, `hu`, `ko`, `lt`, `nl`, `no`, `pt-PT`, `ro`, `sv-SE`
   */
  'RECELLED_SETTINGS_REACT_DEVTOOLS_DESC': TypedIntlMessageGetter<{$b?: HookFunction}>,
  /**
   * Key: `zqMgiI`
   * 
   * ### Definition
   * ```text
   * Failed to download React DevTools.
   * ```
   * 
   * ### Problems
   * 
   * Missing translations: `ar`, `bg`, `da`, `el`, `he`, `hi`, `hr`, `hu`, `ko`, `lt`, `nl`, `no`, `pt-PT`, `ro`, `sv-SE`
   */
  'RECELLED_SETTINGS_REACT_DEVTOOLS_FAILED': TypedIntlMessageGetter<{}>,
  /**
   * Key: `DeRERE`
   * 
   * ### Definition
   * ```text
   * This setting requires you to restart Discord to take effect. Do you want to restart Discord now?
   * ```
   * 
   * ### Problems
   * 
   * Missing translations: `bg`, `da`, `hi`
   */
  'RECELLED_SETTINGS_RESTART': TypedIntlMessageGetter<{}>,
  /**
   * Key: `Ux/XHx`
   * 
   * ### Definition
   * ```text
   * Restart Required
   * ```
   * 
   * ### Problems
   * 
   * Missing translations: `ar`, `bg`, `da`, `el`, `he`, `hi`, `hr`, `hu`, `ko`, `lt`, `nl`, `no`, `pt-PT`, `ro`, `sk`, `sv-SE`, `zh-CN`
   */
  'RECELLED_SETTINGS_RESTART_TITLE': TypedIntlMessageGetter<{}>,
  /**
   * Key: `3P9T6O`
   * 
   * ### Definition
   * ```text
   * Transparent Window
   * ```
   * 
   * ### Problems
   * 
   * Missing translations: `ar`, `bg`, `da`, `el`, `es-ES`, `he`, `hi`, `hr`, `hu`, `id`, `ko`, `lt`, `nl`, `no`, `pt-PT`, `ro`, `sk`, `sv-SE`, `zh-CN`
   */
  'RECELLED_SETTINGS_TRANSPARENT': TypedIntlMessageGetter<{}>,
  /**
   * Key: `XuQLOj`
   * 
   * ### Definition
   * ```text
   * Makes the Discord window transparent, primarily useful for theming. **Requires restart**.
   * ```
   * 
   * ### Problems
   * 
   * Missing translations: `ar`, `bg`, `da`, `el`, `es-ES`, `he`, `hi`, `hr`, `hu`, `id`, `ko`, `lt`, `nl`, `no`, `pt-PT`, `ro`, `sk`, `sv-SE`, `zh-CN`
   */
  'RECELLED_SETTINGS_TRANSPARENT_DESC': TypedIntlMessageGetter<{$b?: HookFunction}>,
  /**
   * Key: `Rl8ZOj`
   * 
   * ### Definition
   * ```text
   * ****WARNING:**** **Hardware acceleration** may need to be turned **off**. In some cases, you may experience a black background, such as when the window is cut off at the top or bottom due to the monitor resolution, or when the development tools are open and docked.
   * ```
   * 
   * ### Problems
   * 
   * Missing translations: `ar`, `bg`, `da`, `el`, `es-ES`, `he`, `hi`, `hr`, `hu`, `id`, `ko`, `lt`, `nl`, `no`, `pt-PT`, `ro`, `sk`, `sv-SE`, `uk`, `vi`, `zh-CN`
   */
  'RECELLED_SETTINGS_TRANSPARENT_ISSUES_LINUX': TypedIntlMessageGetter<{$b?: HookFunction}>,
  /**
   * Key: `DqJLBQ`
   * 
   * ### Definition
   * ```text
   * ****WARNING:**** This will break **window snapping**. In some cases, you may experience a black background, such as when the window is cut off at the top or bottom due to the monitor resolution, or when the development tools are open and docked.
   * ```
   * 
   * ### Problems
   * 
   * Missing translations: `ar`, `bg`, `da`, `el`, `es-ES`, `fr`, `he`, `hi`, `hr`, `hu`, `id`, `ko`, `lt`, `nl`, `no`, `pt-PT`, `ro`, `sk`, `sv-SE`, `uk`, `vi`, `zh-CN`
   */
  'RECELLED_SETTINGS_TRANSPARENT_ISSUES_WINDOWS': TypedIntlMessageGetter<{$b?: HookFunction}>,
  /**
   * Key: `v8UNwc`
   * 
   * ### Definition
   * ```text
   * Snippet Applied
   * ```
   * 
   * ### Problems
   * 
   * Missing translations: `bg`, `da`, `he`, `hi`
   */
  'RECELLED_SNIPPET_APPLIED': TypedIntlMessageGetter<{}>,
  /**
   * Key: `Qgs6Dg`
   * 
   * ### Definition
   * ```text
   * Apply Snippet
   * ```
   * 
   * ### Problems
   * 
   * Missing translations: `bg`, `da`, `hi`
   */
  'RECELLED_SNIPPET_APPLY': TypedIntlMessageGetter<{}>,
  /**
   * Key: `zF718P`
   * 
   * ### Definition
   * ```text
   * Snippet from #css-snippets applied the {date, date, medium} at {date, time, medium}
   * ```
   * 
   * ### Problems
   * 
   * Missing translations: `bg`, `da`, `hi`, `ko`
   */
  'RECELLED_SNIPPET_LINE1': TypedIntlMessageGetter<{date: Date | number}>,
  /**
   * Key: `BZ9caW`
   * 
   * ### Definition
   * ```text
   * Created by {authorTag} ({authorId})
   * ```
   * 
   * ### Problems
   * 
   * Missing translations: `bg`, `da`, `hi`
   */
  'RECELLED_SNIPPET_LINE2': TypedIntlMessageGetter<{authorId: any, authorTag: any}>,
  /**
   * Key: `feJ42t`
   * 
   * ### Definition
   * ```text
   * Store
   * ```
   * 
   * ### Problems
   * 
   * Missing translations: `ar`, `bg`, `da`, `el`, `es-ES`, `fr`, `he`, `hi`, `hr`, `hu`, `id`, `ko`, `lt`, `nl`, `no`, `pt-PT`, `ro`, `ru`, `sk`, `sv-SE`, `vi`, `zh-CN`
   */
  'RECELLED_STORE': TypedIntlMessageGetter<{}>,
  /**
   * Key: `dleZOD`
   * 
   * ### Definition
   * ```text
   * Theme
   * ```
   * 
   * ### Problems
   * 
   * Missing translations: `bg`, `da`, `el`, `he`, `hi`, `hr`, `lt`, `pt-PT`, `ro`
   */
  'RECELLED_THEME': TypedIntlMessageGetter<{}>,
  /**
   * Key: `Dy+63t`
   * 
   * ### Definition
   * ```text
   * Themes
   * ```
   * 
   * ### Problems
   * 
   * Missing translations: `da`, `hi`
   */
  'RECELLED_THEMES': TypedIntlMessageGetter<{}>,
  /**
   * Key: `pEIXbm`
   * 
   * ### Definition
   * ```text
   * Failed to load missing {type}
   * ```
   * 
   * ### Problems
   * 
   * Missing translations: `bg`, `da`, `el`, `he`, `hi`, `hr`, `lt`, `no`, `pt-PT`, `ro`
   */
  'RECELLED_TOAST_ADDONS_LOAD_MISSING_FAILED': TypedIntlMessageGetter<{type: any}>,
  /**
   * Key: `RBbKiY`
   * 
   * ### Definition
   * ```text
   * Loaded missing {type}
   * ```
   * 
   * ### Problems
   * 
   * Missing translations: `bg`, `da`, `el`, `he`, `hi`, `hr`, `lt`, `no`, `pt-PT`, `ro`
   */
  'RECELLED_TOAST_ADDONS_LOAD_MISSING_SUCCESS': TypedIntlMessageGetter<{type: any}>,
  /**
   * Key: `oyG629`
   * 
   * ### Definition
   * ```text
   * Failed to disable {name}
   * ```
   * 
   * ### Problems
   * 
   * Missing translations: `ar`, `bg`, `cs`, `da`, `de`, `el`, `en-GB`, `es-ES`, `fi`, `fr`, `he`, `hi`, `hr`, `hu`, `id`, `it`, `ja`, `ko`, `lt`, `nl`, `no`, `pl`, `pt-BR`, `pt-PT`, `ro`, `ru`, `sk`, `sv-SE`, `tr`, `uk`, `vi`, `zh-CN`, `zh-TW`
   */
  'RECELLED_TOAST_ADDON_DISABLE_FAILED': TypedIntlMessageGetter<{name: any}>,
  /**
   * Key: `tYH3lZ`
   * 
   * ### Definition
   * ```text
   * Disabled {name}
   * ```
   * 
   * ### Problems
   * 
   * Missing translations: `bg`, `da`, `el`, `he`, `hi`, `hr`, `lt`, `no`, `pt-PT`, `ro`
   */
  'RECELLED_TOAST_ADDON_DISABLE_SUCCESS': TypedIntlMessageGetter<{name: any}>,
  /**
   * Key: `w0FOJS`
   * 
   * ### Definition
   * ```text
   * Failed to enable {name}
   * ```
   * 
   * ### Problems
   * 
   * Missing translations: `ar`, `bg`, `cs`, `da`, `de`, `el`, `en-GB`, `es-ES`, `fi`, `fr`, `he`, `hi`, `hr`, `hu`, `id`, `it`, `ja`, `ko`, `lt`, `nl`, `no`, `pl`, `pt-BR`, `pt-PT`, `ro`, `ru`, `sk`, `sv-SE`, `tr`, `uk`, `vi`, `zh-CN`, `zh-TW`
   */
  'RECELLED_TOAST_ADDON_ENABLE_FAILED': TypedIntlMessageGetter<{name: any}>,
  /**
   * Key: `5bTfx8`
   * 
   * ### Definition
   * ```text
   * Enabled {name}
   * ```
   * 
   * ### Problems
   * 
   * Missing translations: `bg`, `da`, `el`, `he`, `hi`, `hr`, `lt`, `no`, `pt-PT`, `ro`
   */
  'RECELLED_TOAST_ADDON_ENABLE_SUCCESS': TypedIntlMessageGetter<{name: any}>,
  /**
   * Key: `hviZgo`
   * 
   * ### Definition
   * ```text
   * Failed to reload {name}
   * ```
   * 
   * ### Problems
   * 
   * Missing translations: `bg`, `da`, `el`, `he`, `hi`, `hr`, `lt`, `no`, `pt-PT`, `ro`
   */
  'RECELLED_TOAST_ADDON_RELOAD_FAILED': TypedIntlMessageGetter<{name: any}>,
  /**
   * Key: `u5OOj4`
   * 
   * ### Definition
   * ```text
   * Reloaded {name}
   * ```
   * 
   * ### Problems
   * 
   * Missing translations: `bg`, `da`, `el`, `he`, `hi`, `hr`, `lt`, `no`, `pt-PT`, `ro`
   */
  'RECELLED_TOAST_ADDON_RELOAD_SUCCESS': TypedIntlMessageGetter<{name: any}>,
  /**
   * Key: `DQ08Jy`
   * 
   * ### Definition
   * ```text
   * Failed to toggle {name}
   * ```
   * 
   * ### Problems
   * 
   * Missing translations: `bg`, `da`, `el`, `he`, `hi`, `hr`, `lt`, `no`, `pt-PT`, `ro`
   */
  'RECELLED_TOAST_ADDON_TOGGLE_FAILED': TypedIntlMessageGetter<{name: any}>,
  /**
   * Key: `tJ3g/P`
   * 
   * ### Definition
   * ```text
   * Failed to uninstall {name}
   * ```
   * 
   * ### Problems
   * 
   * Missing translations: `bg`, `da`, `el`, `he`, `hi`, `hr`, `lt`, `no`, `pt-PT`, `ro`
   */
  'RECELLED_TOAST_ADDON_UNINSTALL_FAILED': TypedIntlMessageGetter<{name: any}>,
  /**
   * Key: `+ymxjo`
   * 
   * ### Definition
   * ```text
   * Uninstalled {name}
   * ```
   * 
   * ### Problems
   * 
   * Missing translations: `bg`, `da`, `el`, `he`, `hi`, `hr`, `lt`, `no`, `pt-PT`, `ro`
   */
  'RECELLED_TOAST_ADDON_UNINSTALL_SUCCESS': TypedIntlMessageGetter<{name: any}>,
  /**
   * Key: `TWskGx`
   * 
   * ### Definition
   * ```text
   * Install canceled.
   * ```
   * 
   * ### Problems
   * 
   * Missing translations: `bg`, `da`, `el`, `he`, `hi`, `hr`, `lt`, `no`, `pt-PT`, `ro`
   */
  'RECELLED_TOAST_INSTALLER_ADDON_CANCELED_INSTALL': TypedIntlMessageGetter<{}>,
  /**
   * Key: `mt8gJi`
   * 
   * ### Definition
   * ```text
   * Failed to get info for addon.
   * ```
   * 
   * ### Problems
   * 
   * Missing translations: `bg`, `da`, `el`, `he`, `hi`, `hr`, `lt`, `no`, `pt-PT`, `ro`
   */
  'RECELLED_TOAST_INSTALLER_ADDON_FETCH_INFO_FAILED': TypedIntlMessageGetter<{}>,
  /**
   * Key: `d/XrCw`
   * 
   * ### Definition
   * ```text
   * Failed to install {name}.
   * ```
   * 
   * ### Problems
   * 
   * Missing translations: `bg`, `da`, `el`, `he`, `hi`, `hr`, `lt`, `no`, `pt-PT`, `ro`
   */
  'RECELLED_TOAST_INSTALLER_ADDON_INSTALL_FAILED': TypedIntlMessageGetter<{name: any}>,
  /**
   * Key: `jVGRtL`
   * 
   * ### Definition
   * ```text
   * {name} installed successfully.
   * ```
   * 
   * ### Problems
   * 
   * Missing translations: `bg`, `da`, `el`, `he`, `hi`, `hr`, `lt`, `no`, `pt-PT`, `ro`
   */
  'RECELLED_TOAST_INSTALLER_ADDON_INSTALL_SUCCESS': TypedIntlMessageGetter<{name: any}>,
  /**
   * Key: `v0I+U1`
   * 
   * ### Definition
   * ```text
   * {name} was installed but could not be loaded.
   * ```
   * 
   * ### Problems
   * 
   * Missing translations: `bg`, `da`, `el`, `he`, `hi`, `hr`, `lt`, `no`, `pt-PT`, `ro`
   */
  'RECELLED_TOAST_INSTALLER_ADDON_LOAD_FAILED': TypedIntlMessageGetter<{name: any}>,
  /**
   * Key: `xhc3vr`
   * 
   * ### Definition
   * ```text
   * Failed to fetch user profile
   * ```
   * 
   * ### Problems
   * 
   * Missing translations: `bg`, `da`, `el`, `he`, `hi`, `hr`, `lt`, `no`, `pt-PT`, `ro`
   */
  'RECELLED_TOAST_PROFILE_FETCH_FAILED': TypedIntlMessageGetter<{}>,
  /**
   * Key: `GIvk/v`
   * 
   * ### Definition
   * ```text
   * Failed to format code
   * ```
   * 
   * ### Problems
   * 
   * Missing translations: `bg`, `da`, `el`, `he`, `hi`, `hr`, `lt`, `no`, `pt-PT`, `ro`
   */
  'RECELLED_TOAST_QUICKCSS_CODE_FORMAT_FAILED': TypedIntlMessageGetter<{}>,
  /**
   * Key: `8kMd9f`
   * 
   * ### Definition
   * ```text
   * Code formatted
   * ```
   * 
   * ### Problems
   * 
   * Missing translations: `bg`, `da`, `el`, `he`, `hi`, `hr`, `lt`, `no`, `pt-PT`, `ro`
   */
  'RECELLED_TOAST_QUICKCSS_CODE_FORMAT_SUCCESS': TypedIntlMessageGetter<{}>,
  /**
   * Key: `lkJ2m5`
   * 
   * ### Definition
   * ```text
   * Quick CSS reloaded
   * ```
   * 
   * ### Problems
   * 
   * Missing translations: `bg`, `da`, `el`, `he`, `hi`, `hr`, `lt`, `no`, `pt-PT`, `ro`
   */
  'RECELLED_TOAST_QUICKCSS_RELOAD': TypedIntlMessageGetter<{}>,
  /**
   * Key: `cmLasb`
   * 
   * ### Definition
   * ```text
   * {count, plural, =1 {# update is} other {# updates are}} available.
   * ```
   * 
   * ### Problems
   * 
   * Missing translations: `ar`, `bg`, `da`, `el`, `he`, `hi`, `hr`, `lt`, `pt-PT`, `ro`
   */
  'RECELLED_UPDATES_AVAILABLE': TypedIntlMessageGetter<{count: any | number | string}>,
  /**
   * Key: `6gniws`
   * 
   * ### Definition
   * ```text
   * Reload Required
   * ```
   * 
   * ### Problems
   * 
   * Missing translations: `da`, `hi`
   */
  'RECELLED_UPDATES_AWAITING_RELOAD_TITLE': TypedIntlMessageGetter<{}>,
  /**
   * Key: `PhJvLi`
   * 
   * ### Definition
   * ```text
   * Check for Updates
   * ```
   * 
   * ### Problems
   * 
   * Missing translations: `da`, `hi`
   */
  'RECELLED_UPDATES_CHECK': TypedIntlMessageGetter<{}>,
  /**
   * Key: `WmdSSE`
   * 
   * ### Definition
   * ```text
   * Enable Updates
   * ```
   * 
   * ### Problems
   * 
   * Missing translations: `da`, `hi`
   */
  'RECELLED_UPDATES_ENABLE': TypedIntlMessageGetter<{}>,
  /**
   * Key: `R7dllZ`
   * 
   * ### Definition
   * ```text
   * Some updates failed!
   * ```
   * 
   * ### Problems
   * 
   * Missing translations: `da`, `hi`
   */
  'RECELLED_UPDATES_FAILED': TypedIntlMessageGetter<{}>,
  /**
   * Key: `phAJ+f`
   * 
   * ### Definition
   * ```text
   * Force Update
   * ```
   * 
   * ### Problems
   * 
   * Missing translations: `da`, `hi`
   */
  'RECELLED_UPDATES_FORCE': TypedIntlMessageGetter<{}>,
  /**
   * Key: `achGoq`
   * 
   * ### Definition
   * ```text
   * Last checked: {date}
   * ```
   * 
   * ### Problems
   * 
   * Missing translations: `da`, `hi`
   */
  'RECELLED_UPDATES_LAST_CHECKED': TypedIntlMessageGetter<{date: any}>,
  /**
   * Key: `tj0sOz`
   * 
   * ### Definition
   * ```text
   * Open Updater
   * ```
   * 
   * ### Problems
   * 
   * Missing translations: `da`, `hi`
   */
  'RECELLED_UPDATES_OPEN_UPDATER': TypedIntlMessageGetter<{}>,
  /**
   * Key: `ovFJTU`
   * 
   * ### Definition
   * ```text
   * Check for updates automatically
   * ```
   * 
   * ### Problems
   * 
   * Missing translations: `da`, `hi`
   */
  'RECELLED_UPDATES_OPTS_AUTO': TypedIntlMessageGetter<{}>,
  /**
   * Key: `Q5Xb1t`
   * 
   * ### Definition
   * ```text
   * ReCelled will automatically check for updates and show you an alert when one is available. Updates will not be installed until you choose to update it. Only official addons will be checked automatically.
   * ```
   * 
   * ### Problems
   * 
   * Missing translations: `bg`, `da`, `hi`
   */
  'RECELLED_UPDATES_OPTS_AUTO_DESC': TypedIntlMessageGetter<{}>,
  /**
   * Key: `hZQ7gY`
   * 
   * ### Definition
   * ```text
   * Open Change Log
   * ```
   * 
   * ### Problems
   * 
   * Missing translations: `da`, `hi`
   */
  'RECELLED_UPDATES_OPTS_CHANGE_LOGS': TypedIntlMessageGetter<{}>,
  /**
   * Key: `EogtLy`
   * 
   * ### Definition
   * ```text
   * Missed the change log, or want to see it again?
   * ```
   * 
   * ### Problems
   * 
   * Missing translations: `da`, `hi`
   */
  'RECELLED_UPDATES_OPTS_CHANGE_LOGS_DESC': TypedIntlMessageGetter<{}>,
  /**
   * Key: `eeOrq6`
   * 
   * ### Definition
   * ```text
   * Update Concurrency Limit
   * ```
   * 
   * ### Problems
   * 
   * Missing translations: `bg`, `da`, `hi`
   */
  'RECELLED_UPDATES_OPTS_CONCURRENCY': TypedIntlMessageGetter<{}>,
  /**
   * Key: `eVfObW`
   * 
   * ### Definition
   * ```text
   * How many concurrent tasks ReCelled will run in background to check for updates. Minimum 1. If unsure, leave 2.
   * ```
   * 
   * ### Problems
   * 
   * Missing translations: `bg`, `da`, `hi`
   */
  'RECELLED_UPDATES_OPTS_CONCURRENCY_DESC': TypedIntlMessageGetter<{}>,
  /**
   * Key: `lfvKQk`
   * 
   * ### Definition
   * ```text
   * Debugging Information
   * ```
   * 
   * ### Problems
   * 
   * Missing translations: `bg`, `da`, `hi`
   */
  'RECELLED_UPDATES_OPTS_DEBUG': TypedIntlMessageGetter<{}>,
  /**
   * Key: `PXMtho`
   * 
   * ### Definition
   * ```text
   * Account:
   * ```
   * 
   * ### Problems
   * 
   * Missing translations: `bg`, `da`, `el`, `he`, `hi`, `hr`, `lt`, `no`, `pt-PT`, `ro`
   */
  'RECELLED_UPDATES_OPTS_DEBUG_ACCOUNT': TypedIntlMessageGetter<{}>,
  /**
   * Key: `WAqSt7`
   * 
   * ### Definition
   * ```text
   * APIs:
   * ```
   * 
   * ### Problems
   * 
   * Missing translations: `bg`, `da`, `el`, `he`, `hi`, `hr`, `lt`, `no`, `pt-PT`, `ro`
   */
  'RECELLED_UPDATES_OPTS_DEBUG_APIS': TypedIntlMessageGetter<{}>,
  /**
   * Key: `iLS2sL`
   * 
   * ### Definition
   * ```text
   * App Version:
   * ```
   * 
   * ### Problems
   * 
   * Missing translations: `bg`, `da`, `el`, `he`, `hi`, `hr`, `lt`, `pt-PT`, `ro`
   */
  'RECELLED_UPDATES_OPTS_DEBUG_APP_VERSION': TypedIntlMessageGetter<{}>,
  /**
   * Key: `jhSM2N`
   * 
   * ### Definition
   * ```text
   * Architecture:
   * ```
   * 
   * ### Problems
   * 
   * Missing translations: `bg`, `da`, `el`, `he`, `hi`, `hr`, `lt`, `pt-PT`, `ro`
   */
  'RECELLED_UPDATES_OPTS_DEBUG_ARCH': TypedIntlMessageGetter<{}>,
  /**
   * Key: `/5OBoa`
   * 
   * ### Definition
   * ```text
   * BetterDiscord Plugins:
   * ```
   * 
   * ### Problems
   * 
   * Missing translations: `bg`, `da`, `el`, `he`, `hi`, `hr`, `lt`, `no`, `pt-PT`, `ro`
   */
  'RECELLED_UPDATES_OPTS_DEBUG_BETTERDISCORD_PLUGINS': TypedIntlMessageGetter<{}>,
  /**
   * Key: `kW5Xnp`
   * 
   * ### Definition
   * ```text
   * Branch:
   * ```
   * 
   * ### Problems
   * 
   * Missing translations: `bg`, `da`, `el`, `he`, `hi`, `hr`, `lt`, `no`, `pt-PT`, `ro`
   */
  'RECELLED_UPDATES_OPTS_DEBUG_BRANCH': TypedIntlMessageGetter<{}>,
  /**
   * Key: `zXw9jo`
   * 
   * ### Definition
   * ```text
   * Build ID:
   * ```
   * 
   * ### Problems
   * 
   * Missing translations: `bg`, `da`, `el`, `he`, `hi`, `hr`, `lt`, `pt-PT`, `ro`
   */
  'RECELLED_UPDATES_OPTS_DEBUG_BUILD_ID': TypedIntlMessageGetter<{}>,
  /**
   * Key: `BnH50t`
   * 
   * ### Definition
   * ```text
   * Build Number:
   * ```
   * 
   * ### Problems
   * 
   * Missing translations: `bg`, `da`, `el`, `he`, `hi`, `hr`, `lt`, `pt-PT`, `ro`
   */
  'RECELLED_UPDATES_OPTS_DEBUG_BUILD_NUMBER': TypedIntlMessageGetter<{}>,
  /**
   * Key: `v+rbHR`
   * 
   * ### Definition
   * ```text
   * Cached Files:
   * ```
   * 
   * ### Problems
   * 
   * Missing translations: `bg`, `da`, `el`, `he`, `hi`, `hr`, `lt`, `no`, `pt-PT`, `ro`
   */
  'RECELLED_UPDATES_OPTS_DEBUG_CACHED_FILES': TypedIntlMessageGetter<{}>,
  /**
   * Key: `AIbuGh`
   * 
   * ### Definition
   * ```text
   * Process Versions
   * ```
   * 
   * ### Problems
   * 
   * Missing translations: `bg`, `da`, `el`, `he`, `hi`, `hr`, `lt`, `pt-PT`, `ro`
   */
  'RECELLED_UPDATES_OPTS_DEBUG_CATEGORY_PROCESS_VERSIONS': TypedIntlMessageGetter<{}>,
  /**
   * Key: `Jb0rR0`
   * 
   * ### Definition
   * ```text
   * System / Discord
   * ```
   * 
   * ### Problems
   * 
   * Missing translations: `bg`, `da`, `el`, `he`, `hi`, `hr`, `lt`, `pt-PT`, `ro`
   */
  'RECELLED_UPDATES_OPTS_DEBUG_CATEGORY_SYSTEM_DISCORD': TypedIntlMessageGetter<{}>,
  /**
   * Key: `GuH+o6`
   * 
   * ### Definition
   * ```text
   * Commands:
   * ```
   * 
   * ### Problems
   * 
   * Missing translations: `bg`, `da`, `el`, `he`, `hi`, `hr`, `lt`, `pt-PT`, `ro`
   */
  'RECELLED_UPDATES_OPTS_DEBUG_COMMANDS': TypedIntlMessageGetter<{}>,
  /**
   * Key: `MSVQMD`
   * 
   * ### Definition
   * ```text
   * Connections:
   * ```
   * 
   * ### Problems
   * 
   * Missing translations: `bg`, `da`, `el`, `he`, `hi`, `hr`, `lt`, `no`, `pt-PT`, `ro`
   */
  'RECELLED_UPDATES_OPTS_DEBUG_CONNECTIONS': TypedIntlMessageGetter<{}>,
  /**
   * Key: `x7HnKC`
   * 
   * ### Definition
   * ```text
   * Copied!
   * ```
   * 
   * ### Problems
   * 
   * Missing translations: `bg`, `da`, `el`, `he`, `hi`, `hr`, `lt`, `pt-PT`, `ro`
   */
  'RECELLED_UPDATES_OPTS_DEBUG_COPIED': TypedIntlMessageGetter<{}>,
  /**
   * Key: `NJ5iU1`
   * 
   * ### Definition
   * ```text
   * Copy
   * ```
   * 
   * ### Problems
   * 
   * Missing translations: `bg`, `da`, `el`, `he`, `hi`, `hr`, `lt`, `pt-PT`, `ro`
   */
  'RECELLED_UPDATES_OPTS_DEBUG_COPY': TypedIntlMessageGetter<{}>,
  /**
   * Key: `K9usk5`
   * 
   * ### Definition
   * ```text
   * Things that you may find useful for troubleshooting or flexing on some stats.
   * ```
   * 
   * ### Problems
   * 
   * Missing translations: `bg`, `da`, `hi`
   */
  'RECELLED_UPDATES_OPTS_DEBUG_DESC': TypedIntlMessageGetter<{}>,
  /**
   * Key: `pdR27u`
   * 
   * ### Definition
   * ```text
   * Discord Path
   * ```
   * 
   * ### Problems
   * 
   * Missing translations: `bg`, `da`, `el`, `he`, `hi`, `hr`, `lt`, `no`, `pt-PT`, `ro`
   */
  'RECELLED_UPDATES_OPTS_DEBUG_DISCORD_PATH': TypedIntlMessageGetter<{}>,
  /**
   * Key: `kzpNen`
   * 
   * ### Definition
   * ```text
   * Distro:
   * ```
   * 
   * ### Problems
   * 
   * Missing translations: `bg`, `da`, `el`, `he`, `hi`, `hr`, `lt`, `pt-PT`, `ro`
   */
  'RECELLED_UPDATES_OPTS_DEBUG_DISTRO': TypedIntlMessageGetter<{}>,
  /**
   * Key: `hQxtQU`
   * 
   * ### Definition
   * ```text
   * Experiments:
   * ```
   * 
   * ### Problems
   * 
   * Missing translations: `bg`, `da`, `el`, `he`, `hi`, `hr`, `lt`, `pt-PT`, `ro`
   */
  'RECELLED_UPDATES_OPTS_DEBUG_EXPERIMENTS': TypedIntlMessageGetter<{}>,
  /**
   * Key: `tM4HS0`
   * 
   * ### Definition
   * ```text
   * Labs:
   * ```
   * 
   * ### Problems
   * 
   * Missing translations: `bg`, `da`, `el`, `he`, `hi`, `hr`, `lt`, `no`, `pt-PT`, `ro`
   */
  'RECELLED_UPDATES_OPTS_DEBUG_LABS': TypedIntlMessageGetter<{}>,
  /**
   * Key: `N853Rk`
   * 
   * ### Definition
   * ```text
   * Latest:
   * ```
   * 
   * ### Problems
   * 
   * Missing translations: `bg`, `da`, `el`, `he`, `hi`, `hr`, `lt`, `no`, `pt-PT`
   */
  'RECELLED_UPDATES_OPTS_DEBUG_LATEST': TypedIntlMessageGetter<{}>,
  /**
   * Key: `fwmYTk`
   * 
   * ### Definition
   * ```text
   * Locale:
   * ```
   * 
   * ### Problems
   * 
   * Missing translations: `bg`, `da`, `el`, `he`, `hi`, `hr`, `lt`, `pt-PT`, `ro`
   */
  'RECELLED_UPDATES_OPTS_DEBUG_LOCALE': TypedIntlMessageGetter<{}>,
  /**
   * Key: `TZumNT`
   * 
   * ### Definition
   * ```text
   * OS:
   * ```
   * 
   * ### Problems
   * 
   * Missing translations: `bg`, `da`, `el`, `he`, `hi`, `hr`, `lt`, `pt-PT`, `ro`
   */
  'RECELLED_UPDATES_OPTS_DEBUG_OS': TypedIntlMessageGetter<{}>,
  /**
   * Key: `ZeKqdn`
   * 
   * ### Definition
   * ```text
   * 64-bit
   * ```
   * 
   * ### Problems
   * 
   * Missing translations: `bg`, `da`, `el`, `he`, `hi`, `hr`, `lt`, `pt-PT`, `ro`
   */
  'RECELLED_UPDATES_OPTS_DEBUG_OS_64BIT': TypedIntlMessageGetter<{}>,
  /**
   * Key: `XYWnzc`
   * 
   * ### Definition
   * ```text
   * Plugins:
   * ```
   * 
   * ### Problems
   * 
   * Missing translations: `bg`, `da`, `el`, `he`, `hi`, `hr`, `lt`, `pt-PT`, `ro`
   */
  'RECELLED_UPDATES_OPTS_DEBUG_PLUGINS': TypedIntlMessageGetter<{}>,
  /**
   * Key: `n0Xfgo`
   * 
   * ### Definition
   * ```text
   * Show less
   * ```
   * 
   * ### Problems
   * 
   * Missing translations: `bg`, `da`, `el`, `he`, `hi`, `hr`, `lt`, `pt-PT`, `ro`
   */
  'RECELLED_UPDATES_OPTS_DEBUG_PLUGINS_SHOW_LESS': TypedIntlMessageGetter<{}>,
  /**
   * Key: `u7Oy8f`
   * 
   * ### Definition
   * ```text
   * Show more
   * ```
   * 
   * ### Problems
   * 
   * Missing translations: `bg`, `da`, `el`, `he`, `hi`, `hr`, `lt`, `pt-PT`, `ro`
   */
  'RECELLED_UPDATES_OPTS_DEBUG_PLUGINS_SHOW_MORE': TypedIntlMessageGetter<{}>,
  /**
   * Key: `WYwhkZ`
   * 
   * ### Definition
   * ```text
   * ReCelled Path
   * ```
   * 
   * ### Problems
   * 
   * Missing translations: `bg`, `da`, `el`, `he`, `hi`, `hr`, `lt`, `no`, `pt-PT`, `ro`
   */
  'RECELLED_UPDATES_OPTS_DEBUG_RECELLED_PATH': TypedIntlMessageGetter<{}>,
  /**
   * Key: `i8tpwc`
   * 
   * ### Definition
   * ```text
   * Release Channel:
   * ```
   * 
   * ### Problems
   * 
   * Missing translations: `bg`, `da`, `el`, `he`, `hi`, `hr`, `lt`, `pt-PT`, `ro`
   */
  'RECELLED_UPDATES_OPTS_DEBUG_RELEASE_CHANNEL': TypedIntlMessageGetter<{}>,
  /**
   * Key: `ZTs1mJ`
   * 
   * ### Definition
   * ```text
   * Revision:
   * ```
   * 
   * ### Problems
   * 
   * Missing translations: `bg`, `da`, `el`, `he`, `hi`, `hr`, `lt`, `no`, `pt-PT`, `ro`
   */
  'RECELLED_UPDATES_OPTS_DEBUG_REVISION': TypedIntlMessageGetter<{}>,
  /**
   * Key: `yxzInJ`
   * 
   * ### Definition
   * ```text
   * Settings:
   * ```
   * 
   * ### Problems
   * 
   * Missing translations: `bg`, `da`, `el`, `he`, `hi`, `hr`, `lt`, `pt-PT`, `ro`
   */
  'RECELLED_UPDATES_OPTS_DEBUG_SETTINGS': TypedIntlMessageGetter<{}>,
  /**
   * Key: `vx/vkZ`
   * 
   * ### Definition
   * ```text
   * Settings Sync:
   * ```
   * 
   * ### Problems
   * 
   * Missing translations: `bg`, `da`, `el`, `he`, `hi`, `hr`, `lt`, `no`, `pt-PT`, `ro`
   */
  'RECELLED_UPDATES_OPTS_DEBUG_SETTINGS_SYNC': TypedIntlMessageGetter<{}>,
  /**
   * Key: `aUDCDw`
   * 
   * ### Definition
   * ```text
   * Themes:
   * ```
   * 
   * ### Problems
   * 
   * Missing translations: `bg`, `da`, `el`, `he`, `hi`, `hr`, `lt`, `no`, `pt-PT`
   */
  'RECELLED_UPDATES_OPTS_DEBUG_THEMES': TypedIntlMessageGetter<{}>,
  /**
   * Key: `Q8neZm`
   * 
   * ### Definition
   * ```text
   * Unauthorized plugins:
   * ```
   * 
   * ### Problems
   * 
   * Missing translations: `bg`, `da`, `el`, `he`, `hi`, `hr`, `lt`, `pt-PT`, `ro`
   */
  'RECELLED_UPDATES_OPTS_DEBUG_UNAUTHORIZED_PLUGINS': TypedIntlMessageGetter<{}>,
  /**
   * Key: `CQIdqa`
   * 
   * ### Definition
   * ```text
   * Upstream:
   * ```
   * 
   * ### Problems
   * 
   * Missing translations: `bg`, `da`, `el`, `he`, `hi`, `hr`, `lt`, `no`, `pt-PT`, `ro`
   */
  'RECELLED_UPDATES_OPTS_DEBUG_UPSTREAM': TypedIntlMessageGetter<{}>,
  /**
   * Key: `XZ6QbW`
   * 
   * ### Definition
   * ```text
   * Update Check Interval
   * ```
   * 
   * ### Problems
   * 
   * Missing translations: `da`, `hi`
   */
  'RECELLED_UPDATES_OPTS_INTERVAL': TypedIntlMessageGetter<{}>,
  /**
   * Key: `mELQ4+`
   * 
   * ### Definition
   * ```text
   * How frequently ReCelled will check for updates. Minimum 10 minutes.
   * ```
   * 
   * ### Problems
   * 
   * Missing translations: `bg`, `da`, `hi`
   */
  'RECELLED_UPDATES_OPTS_INTERVAL_DESC': TypedIntlMessageGetter<{}>,
  /**
   * Key: `sXlAJC`
   * 
   * ### Definition
   * ```text
   * Change Release Channel
   * ```
   * 
   * ### Problems
   * 
   * Missing translations: `bg`, `da`, `hi`
   */
  'RECELLED_UPDATES_OPTS_RELEASE': TypedIntlMessageGetter<{}>,
  /**
   * Key: `ya7lRU`
   * 
   * ### Definition
   * ```text
   * You can choose between the stable branch, or the development branch. Stable branch will only get major updates, security and critical updates. If unsure, stay on stable.
   * ```
   * 
   * ### Problems
   * 
   * Missing translations: `bg`, `da`, `hi`
   */
  'RECELLED_UPDATES_OPTS_RELEASE_DESC': TypedIntlMessageGetter<{}>,
  /**
   * Key: `d03zj4`
   * 
   * ### Definition
   * ```text
   * Switch to development branch
   * ```
   * 
   * ### Problems
   * 
   * Missing translations: `bg`, `da`, `hi`
   */
  'RECELLED_UPDATES_OPTS_RELEASE_DEVELOP_BTN': TypedIntlMessageGetter<{}>,
  /**
   * Key: `Ksh8kJ`
   * 
   * ### Definition
   * ```text
   * Are you sure you want to change your release channel? ReCelled will reload your Discord client.
   * ```
   * 
   * ### Problems
   * 
   * Missing translations: `bg`, `da`, `hi`
   */
  'RECELLED_UPDATES_OPTS_RELEASE_MODAL': TypedIntlMessageGetter<{}>,
  /**
   * Key: `YiSV9P`
   * 
   * ### Definition
   * ```text
   * Change release channel
   * ```
   * 
   * ### Problems
   * 
   * Missing translations: `bg`, `da`, `hi`
   */
  'RECELLED_UPDATES_OPTS_RELEASE_MODAL_HEADER': TypedIntlMessageGetter<{}>,
  /**
   * Key: `oiAHo6`
   * 
   * ### Definition
   * ```text
   * Switch to stable
   * ```
   * 
   * ### Problems
   * 
   * Missing translations: `da`, `hi`
   */
  'RECELLED_UPDATES_OPTS_RELEASE_STABLE_BTN': TypedIntlMessageGetter<{}>,
  /**
   * Key: `ng7lpq`
   * 
   * ### Definition
   * ```text
   * Switch
   * ```
   * 
   * ### Problems
   * 
   * Missing translations: `da`, `hi`
   */
  'RECELLED_UPDATES_OPTS_RELEASE_SWITCH': TypedIntlMessageGetter<{}>,
  /**
   * Key: `prcDPT`
   * 
   * ### Definition
   * ```text
   * Show update checker toast
   * ```
   * 
   * ### Problems
   * 
   * Missing translations: `da`, `he`, `hi`, `no`
   */
  'RECELLED_UPDATES_OPTS_TOAST_ENABLED': TypedIntlMessageGetter<{}>,
  /**
   * Key: `a671IS`
   * 
   * ### Definition
   * ```text
   * Show an overlay over the client which says updates are being checked for, and if updates are found, prompt you to update. Only applies if update in background is disabled.
   * ```
   * 
   * ### Problems
   * 
   * Missing translations: `bg`, `da`, `he`, `hi`, `no`
   */
  'RECELLED_UPDATES_OPTS_TOAST_ENABLED_DESC': TypedIntlMessageGetter<{}>,
  /**
   * Key: `8IdVW1`
   * 
   * ### Definition
   * ```text
   * Some updates failed!
   * ```
   * 
   * ### Problems
   * 
   * Missing translations: `bg`, `da`, `el`, `he`, `hi`, `hr`, `lt`, `no`, `pt-PT`, `ro`
   */
  'RECELLED_UPDATES_TOAST_FAILED_ALL': TypedIntlMessageGetter<{}>,
  /**
   * Key: `SZJN0t`
   * 
   * ### Definition
   * ```text
   * Update failed!
   * ```
   * 
   * ### Problems
   * 
   * Missing translations: `bg`, `da`, `el`, `he`, `hi`, `hr`, `lt`, `no`, `pt-PT`, `ro`
   */
  'RECELLED_UPDATES_TOAST_FAILED_ONE': TypedIntlMessageGetter<{}>,
  /**
   * Key: `NBjP0N`
   * 
   * ### Definition
   * ```text
   * {count, plural, =1 {# new update} other {# new updates}} available!
   * ```
   * 
   * ### Problems
   * 
   * Missing translations: `bg`, `da`, `el`, `he`, `hi`, `hr`, `lt`, `no`, `pt-PT`, `ro`, `zh-CN`
   */
  'RECELLED_UPDATES_TOAST_NEW': TypedIntlMessageGetter<{count: any | number | string}>,
  /**
   * Key: `QGsrGB`
   * 
   * ### Definition
   * ```text
   * No new updates available.
   * ```
   * 
   * ### Problems
   * 
   * Missing translations: `bg`, `da`, `el`, `he`, `hi`, `hr`, `lt`, `no`, `pt-PT`, `ro`
   */
  'RECELLED_UPDATES_TOAST_NO_NEW': TypedIntlMessageGetter<{}>,
  /**
   * Key: `HnLi7e`
   * 
   * ### Definition
   * ```text
   * All updates completed successfully.
   * ```
   * 
   * ### Problems
   * 
   * Missing translations: `bg`, `da`, `el`, `he`, `hi`, `hr`, `lt`, `no`, `pt-PT`, `ro`
   */
  'RECELLED_UPDATES_TOAST_SUCCESS_ALL': TypedIntlMessageGetter<{}>,
  /**
   * Key: `gMn8Mz`
   * 
   * ### Definition
   * ```text
   * Update completed successfully.
   * ```
   * 
   * ### Problems
   * 
   * Missing translations: `bg`, `da`, `el`, `he`, `hi`, `hr`, `lt`, `no`, `pt-PT`, `ro`
   */
  'RECELLED_UPDATES_TOAST_SUCCESS_ONE': TypedIntlMessageGetter<{}>,
  /**
   * Key: `dr3lqK`
   * 
   * ### Definition
   * ```text
   * Update
   * ```
   * 
   * ### Problems
   * 
   * Missing translations: `da`, `hi`
   */
  'RECELLED_UPDATES_UPDATE': TypedIntlMessageGetter<{}>,
  /**
   * Key: `Ywk+W1`
   * 
   * ### Definition
   * ```text
   * Updater
   * ```
   * 
   * ### Problems
   * 
   * Missing translations: `bg`, `da`, `el`, `he`, `hi`, `hr`, `lt`, `no`, `pt-PT`, `ro`
   */
  'RECELLED_UPDATES_UPDATER': TypedIntlMessageGetter<{}>,
  /**
   * Key: `OV5nm5`
   * 
   * ### Definition
   * ```text
   * Update All
   * ```
   * 
   * ### Problems
   * 
   * Missing translations: `bg`, `da`, `el`, `he`, `hi`, `hr`, `lt`, `no`, `pt-PT`, `ro`
   */
  'RECELLED_UPDATES_UPDATE_ALL': TypedIntlMessageGetter<{}>,
  /**
   * Key: `unTTAg`
   * 
   * ### Definition
   * ```text
   * Update
   * ```
   * 
   * ### Problems
   * 
   * Missing translations: `bg`, `da`, `el`, `he`, `hi`, `hr`, `lt`, `no`, `pt-PT`, `ro`
   */
  'RECELLED_UPDATES_UPDATE_NOUN': TypedIntlMessageGetter<{}>,
  /**
   * Key: `Ir3pXF`
   * 
   * ### Definition
   * ```text
   * Update to {version}
   * ```
   * 
   * ### Problems
   * 
   * Missing translations: `bg`, `da`, `el`, `he`, `hi`, `hr`, `lt`, `no`, `pt-PT`, `ro`
   */
  'RECELLED_UPDATES_UPDATE_TO': TypedIntlMessageGetter<{version: any}>,
  /**
   * Key: `vyQxoa`
   * 
   * ### Definition
   * ```text
   * Updating ReCelled…
   * ```
   * 
   * ### Problems
   * 
   * Missing translations: `da`, `hi`
   */
  'RECELLED_UPDATES_UPDATING': TypedIntlMessageGetter<{}>,
  /**
   * Key: `4ipA29`
   * 
   * ### Definition
   * ```text
   * Updating…
   * ```
   * 
   * ### Problems
   * 
   * Missing translations: `da`, `hi`
   */
  'RECELLED_UPDATES_UPDATING_ITEM': TypedIntlMessageGetter<{}>,
  /**
   * Key: `PATV9P`
   * 
   * ### Definition
   * ```text
   * Everything is up to date.
   * ```
   * 
   * ### Problems
   * 
   * Missing translations: `da`, `he`, `hi`
   */
  'RECELLED_UPDATES_UP_TO_DATE': TypedIntlMessageGetter<{}>,
  /**
   * Key: `cyjGoa`
   * 
   * ### Definition
   * ```text
   * ReCelled {version, select, dev {[DEV MODE]} other {v{version}}}
   * ```
   * 
   * ### Problems
   * 
   * Missing translations: `ar`, `bg`, `da`, `el`, `he`, `hi`, `hr`, `hu`, `lt`, `no`, `pt-PT`, `ro`, `sv-SE`
   */
  'RECELLED_VERSION': TypedIntlMessageGetter<{version: 'dev' | any | string}>,
  /**
   * Key: `PTGJUF`
   * 
   * ### Definition
   * ```text
   * View {count, plural, =1 {# Update} other {# Updates}}
   * ```
   * 
   * ### Problems
   * 
   * Missing translations: `ar`, `bg`, `da`, `el`, `he`, `hi`, `hr`, `hu`, `ko`, `lt`, `no`, `pt-PT`, `ro`, `sv-SE`, `zh-CN`
   */
  'RECELLED_VIEW_UPDATES': TypedIntlMessageGetter<{count: any | number | string}>,
};
export default messages;